### ISSUE TITLE
/

### ISSUE THREAD

**Issue by luckcius** [dgadelha/Portugol-Webstudio#100]
Algoritmo VerificarVogal
Var
   letra: caractere

Inicio
   Escreva("Digite uma letra: ")
   leia(letra)
   
   // Converte a letra para minúscula para facilitar a comparação
   letra <- paraMinuscula(letra)
   
   // Verifica se a letra é uma vogal
   Se letra = 'a' ou letra = 'e' ou letra = 'i' ou letra = 'o' ou letra = 'u' Então
      Escreva("A letra digitada é uma vogal.")
   Senão
      Escreva("A letra digitada não é uma vogal.")
   FimSe
FimAlgoritmo

**Comment by dgadelha** [comment]
Olá, este código não está no padrão Portugol da UNIVALI.
