### ISSUE TITLE
Divisor

### ISSUE THREAD

**Issue by LSouza79** [dgadelha/Portugol-Webstudio#101]
programa {
  funcao inicio() {
    inteiro valor1, valor2, resto = 0

    escreveu
    ("olá! Vamos verificar se um valor é divisor de outro. Digite dois valores: \n")
    escreva
    ("Digite o primeiro valor:")
    leia
    (valor1)
    escreva
    ("\nDigite o segundo valor:")

    se 
    (valor1 > valor2){
       resto = valor1 % valor2
    }
    se
    (valor2 > valor1){
        resto = valor2 % valor1
    }
    se
    (resto == 0){
       escreva
       ("\nÉ divisor!")
    } 
  }
}

**Comment by dgadelha** [comment]
O correto é `escreva` ao invés de `escreveu`
