### ISSUE TITLE
portugol

### ISSUE THREAD

**Issue by jonathan-nascimento51** [dgadelha/Portugol-Webstudio#104]
programa {
  funcao inicio() {
    programa VerificaIdade;

    var
      idade: inteiro;

    inicio
      escreva("Informe sua idade: ");
      leia(idade);
  
  se idade < 18 entao
    escreva("Você é menor de idade.")
  senao
    escreva("Você é maior de idade.");
  fimse
fim.
  }
}

**Comment by dgadelha** [comment]
Olá, este código não está no padrão Portugol da UNIVALI, está no estilo Algol.
