### ISSUE TITLE
controle de estoque

### ISSUE THREAD

**Issue by flsbiel** [dgadelha/Portugol-Webstudio#109]
algoritmo ControleDeEstoque

var
    est: vetor[1..100] de caractere
    tam: inteiro

procedimento addProd()
    var
        prod: caractere
    
    escreva("Nome do produto: ")
    leia(prod)
    
    tam <- tam + 1
    est[tam] <- prod
    
    escreva("Produto adicionado.")
fim_procedimento

procedimento list()
    var
        i: inteiro
    
    escreva("----- Ver estoque -----")
    para i de 1 ate tam faca
        escreva(i, ". ", est[i])
    fim_para
    escreva("-----------------------")
fim_procedimento

funcao inicio()
    var
        op: inteiro
    
    tam <- 0
    
    repita
        escreva("----- Controle de Estoque -----")
        escreva("1. Adicionar Produto")
        escreva("2. Listar Produtos")
        escreva("0. Sair")
        escreva("Escolha uma opção: ")
        leia(op)
        
        escolha op
            caso 1
                addProd()
            caso 2
                list()
            caso 0
                escreva("Saindo...")
        fim_escolha
    ate op = 0
fim_funcao

**Comment by dgadelha** [comment]
Olá, este código não está no padrão Portugol da UNIVALI, está no estilo Algol.
