### ISSUE TITLE
Teste Portugol

### ISSUE THREAD

**Issue by Mitsuya-Dev** [dgadelha/Portugol-Webstudio#111]
programa {
    funcao inicio() {
        inteiro num_meses = 12
        inteiro num_semanas = 4
        real vendas[12][4]
        real total_meses[12]
        real total_anual

        // Preencha a matriz com os valores de venda semanais
        para (inteiro i = 1; i <= num_meses; i++) {
            escreva("Insira as vendas para o mes ", i, ":\n")
            para (inteiro j = 1; j <= num_semanas; j++) {
                escreva("Semana ", j, ": R$ ")
                leia(vendas[i][j])
            }
        }

        // Calcule o total vendido em cada mes
        para (inteiro i = 1; i <= num_meses; i++) {
            total_meses[i] = 0
            para (inteiro j = 1; j <= num_semanas; j++) {
                total_meses[i] = total_meses[i] + vendas[i][j]
            }
        }

        // Calcule o total vendido no ano
        total_anual = 0
        para (inteiro i = 1; i <= num_meses; i++) {
            total_anual = total_anual + total_meses[i]
        }

        // Imprima o total vendido em cada mes
        para (inteiro i = 1; i <= num_meses; i++) {
            escreva("Total vendido no mes ", i, ": R$ ", total_meses[i]:.2f, "\n")
        }

        // Imprima o total vendido no ano
        escreva("Total vendido no ano: R$ ", total_anual:.2f)
    }
}

**Comment by dgadelha** [comment]
Olá, o erro está nos `:.2f`, acredito que esteja tentando fazer um format do número, mas isso não existe no Portugol da UNIVALI.
