### ISSUE TITLE
Erro no-sense

### ISSUE THREAD

**Issue by umquark** [dgadelha/Portugol-Webstudio#119]
⛔ O seu código possui 1 erro de compilação:
   - A variável 'soma' esperava ser atribuída com um valor do tipo 'real', mas recebeu um valor do tipo 'inteiro' (linha 6, posição 5)

⚠️ Durante essa fase experimental, o código ainda será executado mesmo com erros, porém se não corrigi-los, a execução abaixo pode exibir mensagens de erro em inglês ou sem explicação.
   Caso acredite que o erro não faça sentido, por favor, abra uma issue em https://github.com/dgadelha/Portugol-Webstudio/issues/new e anexe o código que você está tentando executar.

programa {
  funcao inicio() {
    inteiro iteracao_atual
    real soma, num

    soma = 0
    iteracao_atual = 0

    enquanto(iteracao_atual < 3)
    {
      escreva("Digite um número: ")
      leia(num)
      soma += num
      iteracao_atual += 1
    }
    escreva("A soma dos números é: " + soma)
    
  }
}

**Comment by dgadelha** [comment]
Trackeando na #85
