### ISSUE TITLE
erro in portugol studio.

### ISSUE THREAD

**Issue by vinii004** [dgadelha/Portugol-Webstudio#124]
Hello, I've been struggling with my pseudocode for almost a month, trying to fix it without success. If you could correct the errors and send me the running program, I would be very grateful, as it is for my college assignment. Thank you for your attention.

programa {
    inclua biblioteca Util --> u

    funcao inicio() {
        inteiro pontos = 0
        inteiro escolhaDificuldade
        inteiro numeroSecreto
        inteiro tentativas
        inteiro limite

        escreva("========================")
         escreva("insira seu nome")
         leia(nome)
        escreva("Bem-vindo ao jogo de adivinhação!")
        escreva("Escolha a dificuldade: ")
        escreva("1 - Fácil")
        escreva("2 - Médio")
        escreva("3 - Difícil")
        escreva("========================")

        leia(escolhaDificuldade)

        escolha(escolhaDificuldade) {
            caso 1:
                numeroSecreto = u.sorteia(1, 10)
                tentativas = 10
                limite = 10
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
            caso 2:
                numeroSecreto = u.sorteia(1, 25)
                tentativas = 8
                limite = 25
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
            caso 3:
                numeroSecreto = u.sorteia(1, 50)
                tentativas = 5
                limite = 50
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
            caso contrario:
                escreva("Escolha inválida.")
                retorne
        }

        se (pontos >= 1){
            escreva("Você passou para a próxima fase!")
            escreva("Adivinhe um número de 1 a 200 em 15 tentativas:")
            numeroSecreto = u.sorteia(1, 200)
            tentativas = 15
            pontos += jogarJogo(numeroSecreto, tentativas, 200)
        }         
        senao{
            escreva("Você não passou para a próxima fase. Fim do jogo.")
            retorne
        }

        se (pontos >= 2){
            escreva("Você passou para a última fase!")
            escreva("Escolha a dificuldade:")
            escreva("1 - Média")
            escreva("2 - Difícil")

            leia(escolhaDificuldade)

            escolha(escolhaDificuldade) {
                caso 1:
                    numeroSecreto = u.sorteia(1, 75)
                    tentativas = 10
                    limite = 75
                caso 2:
                    numeroSecreto = u.sorteia(1, 250)
                    tentativas = 8
                    limite = 250
                caso contrario:
                    escreva("Escolha inválida.")
                    retorne
            }

            pontos += jogarJogo(numeroSecreto, tentativas, limite)

            se (pontos >= 3){
                escreva("Parabéns! Você passou em todas as fases!")
            }
            senao {
                escreva("Você não passou em todas as fases. Fim do jogo.")
            }
        }
        senao{
            escreva("Você não passou para a última fase. Fim do jogo.")
        }
    }

    funcao jogarJogo(inteiro numeroSecreto, inteiro tentativas, inteiro limite) {
        inteiro tentativasRestantes = tentativas
        inteiro palpite

        enquanto (tentativasRestantes > 0) faca {
            escreva("Digite um palpite (entre 1 e ", limite, "): ")
            leia(palpite)

            se (palpite < 1) ou (palpite > limite){
                escreva("Palpite inválido. Tente novamente.")
            }
            senao se (palpite = numeroSecreto){
                escreva("Parabéns! Você acertou o número secreto.")
                retorne 1
            }
            senao (palpite < numeroSecreto){
                escreva("Tentativa ", (tentativas - tentativasRestantes + 1), ": Palpite muito baixo. Tentativas restantes: ", (tentativasRestantes - 1))
            }
            senao{
                escreva("Tentativa ", (tentativas - tentativasRestantes + 1), ": Palpite muito alto. Tentativas restantes: ", (tentativasRestantes - 1))
            }

            tentativasRestantes = tentativasRestantes - 1
        }

        escreva("Você usou todas as tentativas. O número secreto era: ", numeroSecreto)
        retorne 0
    }
}

**Comment by dgadelha** [comment]
Olá,

Segue a versão corrigida do seu código:

```portugol
programa {
    inclua biblioteca Util --> u

    funcao inicio() {
        inteiro pontos = 0
        inteiro escolhaDificuldade
        inteiro numeroSecreto
        inteiro tentativas
        inteiro limite
        cadeia nome

        escreva("========================")
         escreva("insira seu nome")
         leia(nome)
        escreva("Bem-vindo ao jogo de adivinhação!")
        escreva("Escolha a dificuldade: ")
        escreva("1 - Fácil")
        escreva("2 - Médio")
        escreva("3 - Difícil")
        escreva("========================")

        leia(escolhaDificuldade)

        escolha(escolhaDificuldade) {
            caso 1:
                numeroSecreto = u.sorteia(1, 10)
                tentativas = 10
                limite = 10
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
                pare
            caso 2:
                numeroSecreto = u.sorteia(1, 25)
                tentativas = 8
                limite = 25
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
                pare
            caso 3:
                numeroSecreto = u.sorteia(1, 50)
                tentativas = 5
                limite = 50
                pontos += jogarJogo(numeroSecreto, tentativas, limite)
                pare
            caso contrario:
                escreva("Escolha inválida.")
                retorne
        }

        se (pontos >= 1){
            escreva("Você passou para a próxima fase!")
            escreva("Adivinhe um número de 1 a 200 em 15 tentativas:")
            numeroSecreto = u.sorteia(1, 200)
            tentativas = 15
            pontos += jogarJogo(numeroSecreto, tentativas, 200)
        }         
        senao{
            escreva("Você não passou para a próxima fase. Fim do jogo.")
            retorne
        }

        se (pontos >= 2){
            escreva("Você passou para a última fase!")
            escreva("Escolha a dificuldade:")
            escreva("1 - Média")
            escreva("2 - Difícil")

            leia(escolhaDificuldade)

            escolha(escolhaDificuldade) {
                caso 1:
                    numeroSecreto = u.sorteia(1, 75)
                    tentativas = 10
                    limite = 75
                    pare
                caso 2:
                    numeroSecreto = u.sorteia(1, 250)
                    tentativas = 8
                    limite = 250
                    pare
                caso contrario:
                    escreva("Escolha inválida.")
                    retorne
            }

            pontos += jogarJogo(numeroSecreto, tentativas, limite)

            se (pontos >= 3){
                escreva("Parabéns! Você passou em todas as fases!")
            }
            senao {
                escreva("Você não passou em todas as fases. Fim do jogo.")
            }
        }
        senao{
            escreva("Você não passou para a última fase. Fim do jogo.")
        }
    }

    funcao inteiro jogarJogo(inteiro numeroSecreto, inteiro tentativas, inteiro limite) {
        inteiro tentativasRestantes = tentativas
        inteiro palpite

        enquanto (tentativasRestantes > 0) {
            escreva("Digite um palpite (entre 1 e ", limite, "): ")
            leia(palpite)

            se ((palpite < 1) ou (palpite > limite)) {
                escreva("Palpite inválido. Tente novamente.")
            }
            senao se (palpite == numeroSecreto){
                escreva("Parabéns! Você acertou o número secreto.")
                retorne 1
            }
            senao se (palpite < numeroSecreto){
                escreva("Tentativa ", (tentativas - tentativasRestantes + 1), ": Palpite muito baixo. Tentativas restantes: ", (tentativasRestantes - 1))
            }
            senao{
                escreva("Tentativa ", (tentativas - tentativasRestantes + 1), ": Palpite muito alto. Tentativas restantes: ", (tentativasRestantes - 1))
            }

            tentativasRestantes = tentativasRestantes - 1
        }

        escreva("Você usou todas as tentativas. O número secreto era: ", numeroSecreto)
        retorne 0
    }
}
```

As correções feitas foram:

- Haviam dois `senao` na sua última função
- Esqueceu do `pare` no escolha-caso
- Um `se` com duas condições deve estar englobado entre parênteses
- Faltou definir o tipo de retorno da função `jogarJogo`
- Faltou declarar a variável `nome`

Além disso, é necessário adicionar um `\n` no texto da função `escreva` para pular linha caso seja do seu interesse.

**Comment by vinii004** [comment]
mano mt obg pqp, salvou mt de vdd


Em ter., 21 de nov. de 2023 às 20:03, Douglas Gadêlha <
***@***.***> escreveu:
