### ISSUE TITLE
Porque está dando errado?

### ISSUE THREAD

**Issue by CauaFMartins** [dgadelha/Portugol-Webstudio#129]
programa {
inclua biblioteca Matematica-->mat
  funcao inicio() {
    const real pLapis =1.99
    const real pBorracha =1.49
    const real pCaneta =2.49

    inteiro quantidadeLapis, quantidadeBorracha, quantidadeCaneta
    real ttlLapis, ttlBorracha, ttlCaneta, ttlGeral

    cadeia nomeCliente

    escreva("Digite o nome do cliente:\n")
    leia(nomeCliente)

    escreva("Digite a quantidade de lápis:\n")
    leia(quantidadeLapis)

    escreva("Digite a quantidade de borrachas:\n")
    leia(quantidadeBorracha)

    escreva("Digite a quantidade de canetas:\n")
    leia(quantidadeCaneta)

    limpa()

    ttlLapis = pLapis * quantidadeLapis
    ttlLapis = mat.arredondar(ttlLapis,2)

    ttlBorracha= pBorracha * quantidadeBorracha
    ttlBorracha= mat.arredondar(ttlBorracha,2)

    ttlCaneta  = pCaneta * quantidadeCaneta
    ttlCaneta = mat.arredondar(ttlCaneta,2)

    ttlGeral = ttlLapis +ttlBorracha+ ttlCaneta
    ttlGeral = mat.arredondar(ttlGeral,2)

    escreva("---------------------------Relatório---------------------------\n")
    escreva("Lapis...:Vl Unit: R$ "+pLapis+"\tQTD:"+quantidadeLapis+"\tTotal R$" +ttlLapis"\n")
    escreva("Borracha...:Vl Unit: R$ "+pBorracha+"\tQTD:"+quantidadeBorracha+"\tTotal R$" +ttlBorracha"\n")
    escreva("Caneta...:Vl Unit: R$ "+pCaneta+"\tQTD:"+quantidadeCaneta+"\tTotal R$" +ttlCaneta"\n")
   

  }
}

**Comment by dgadelha** [comment]
Olá,

Esqueceu do `+` antes do `\n`:

```portugol
    escreva("Lapis...:Vl Unit: R$ "+pLapis+"\tQTD:"+quantidadeLapis+"\tTotal R$" +ttlLapis+"\n")
    escreva("Borracha...:Vl Unit: R$ "+pBorracha+"\tQTD:"+quantidadeBorracha+"\tTotal R$" +ttlBorracha+"\n")
    escreva("Caneta...:Vl Unit: R$ "+pCaneta+"\tQTD:"+quantidadeCaneta+"\tTotal R$" +ttlCaneta+"\n")
```
