### ISSUE TITLE
problemas no código no portugol studio

### ISSUE THREAD

**Issue by moabgstz** [dgadelha/Portugol-Webstudio#133]
Algoritmo "Soma dos elementos ímpares e pares"
Var
   A: vetor[1..5] de inteiro
   soma_pares, soma_impares, i: inteiro
Inicio
   soma_pares <- 0
   soma_impares <- 0

   Para i <- 1 ate 5 faca
      Escreva("Digite o ", i, "º número: ")
      Leia(A[i])

      Se A[i] mod 2 = 0 Entao
         soma_pares <- soma_pares + A[i]
      Senao
         soma_impares <- soma_impares + A[i]
      FimSe
   FimPara

   Escreva("Soma dos elementos pares: ", soma_pares)
   Escreva("Soma dos elementos ímpares: ", soma_impares)
FimAlgoritmo

**Comment by dgadelha** [comment]
Olá, este código não está no padrão Portugol da UNIVALI.
