### ISSUE TITLE
Problema com parênteses.

### ISSUE THREAD

**Issue by RoronoaDmiguel** [dgadelha/Portugol-Webstudio#138]
![imagem_2023-12-20_172115392](https://github.com/dgadelha/Portugol-Webstudio/assets/154469202/402f5092-a5d2-40f3-ba19-91f6e5925117)

Não consigo identificar, o porque da invalidade do meu parênteses. Creio eu, que o usei corretamente. Por favor, me ajude.

**Comment by dgadelha** [comment]
Olá! No `escreva` da linha 36, você esqueceu do `+` entre `"` e `media`, sendo o correto: `escreva("a média é " + media)`

**Comment by RoronoaDmiguel** [comment]
Agora o programa funcionou perfeitamente, muito obrigado!
Eu ainda não aprendi o uso do "+", dessa forma.
Vou tentar entender melhor!
