### ISSUE TITLE
Redesenhar a interface

### ISSUE THREAD

**Issue by dgadelha** [dgadelha/Portugol-Webstudio#14]
Eu tava com essa ideia na cabeça tem um tempo já.

A ideia seria fazer algo usando essas 'tecnologias novas' aí que esses "web developers" _de hoje em dia_ usam Angular<sup>4</sup> (e as nojeiras que vem junto, ex: webpack/algo do tipo), NodeJS e o resto aí.

Tô botando aí sem data pra terminar nem eu sei se/quando vou fazer isso, mas se for pra refazermos isso aí em Angular, vamos fugir muito da interface do Portugol Studio original (da UNIVALI), então também fica a dúvida se vale a pena fazer isso ou manter a ~gambiarra~ interface atual.

**Comment by AlissonSteffens** [comment]
A interface atual foi montada com [um monte de artigo](https://pt.wikipedia.org/wiki/Portugol_Studio) de base para ser mais fácil de usar pela rapazi. At least a rapazi da univali;
Não sei até que ponto é legal mudar muito ela.
Mas de qualquer forma, se precisar de ajuda pra montar uma nova :s mudamos nos dois lugares :)

**Comment by dgadelha** [comment]
Isso foi deixado pra ser feito em outro projeto.
