### ISSUE TITLE
Erro ao reconhecer valor do tipo Lógico

### ISSUE THREAD

**Issue by djonathas** [dgadelha/Portugol-Webstudio#141]
Dentro da ajuda, no tópico do tipo de dado Lógico, ao colocar para testar o código de exemplo é informado um erro de que o valor passado para a variável é do tipo "vazio", mas é o valor é do tipo lógico, tanto que o código funciona como esperado, apesar de informar o erro
![Captura de tela de 2024-01-09 10-38-03](https://github.com/dgadelha/Portugol-Webstudio/assets/2695960/a34741e7-3499-4a1a-a5e7-453bea64074d)

**Comment by dgadelha** [comment]
Obrigado pelo report! Problema corrigido ;)
