### ISSUE TITLE
onde etá o erro ?

### ISSUE THREAD

**Issue by joannespaullus** [dgadelha/Portugol-Webstudio#142]
programa {

       funcao inicio() {
        
                 inteiro vet = 0
                 sorteia()
                 preenche (vet)
                 escreva("Variavel antes:\n")
                 exibe (vet)
                 escreva("\n\nVariavel após:\n")         
                 exibe (vet)
                 escreva("\n")
          }
          funcao preenche (inteiro &v) {
                v = sorteia (1, 100)
          }
          funcao exibe (inteiro v) {
                      escreva (v, " ")
                      v = 5
          }
          
   }

**Comment by dgadelha** [comment]
Olá! Ficou faltando a importação da biblioteca Util
