### ISSUE TITLE
Reestruturar links e arquivos de Ajuda

### ISSUE THREAD

**Issue by guiscaranse** [dgadelha/Portugol-Webstudio#15]
O repositório do [Portugol Studio](https://github.com/UNIVALI-LITE/Portugol-Studio) passou para uma reestruturação, todos os repos antigos foram deletados, então o submodule de "Recursos" e os links para imagens dos antigos repositórios, deixarão de funcionar.

Progresso:

- [x] ~Remover submodule~ (https://github.com/dgadelha/Portugol-Webstudio/commit/3f8ff299eea04c55b845d25996a0beacc822d58c)
- [x] ~Usar a nova pasta de recursos~ (https://github.com/dgadelha/Portugol-Webstudio/commit/3f8ff299eea04c55b845d25996a0beacc822d58c)
- [x] ~Recriar índice do Ajuda **Automaticamente**~ (https://github.com/dgadelha/Portugol-Webstudio/commit/195fe6b42a64697422e30cd52470fb9f72f6a5b0)
- [x] ~Recriar índice de Exemplos **Automaticamente**~ (https://github.com/dgadelha/Portugol-Webstudio/commit/6bee7dca51684f0f36c14d4ec87ea7dd4e16a506)

**Comment by dgadelha** [comment]
Ajeitei os ícones, vou pensar o que eu faço pra esse negoço desse Recursos.

**Comment by AlissonSteffens** [comment]
se vcs quiserem usar os antigos está aqui https://github.com/UNIVALI-LITE-BACKUP

**Comment by dgadelha** [comment]
Lembrar a mim mesmo: https://github.com/UNIVALI-LITE/Portugol-Studio/tree/master/ide/src/main/assets
