### ISSUE TITLE
Estou tendo um erro no portugol e não estou entendendo. O erro esta sendo na linha 24.

### ISSUE THREAD

**Issue by patrikdutraa** [dgadelha/Portugol-Webstudio#155]
programa {
    funcao inicio() {
        inteiro a;
        inteiro b;
        inteiro r;
        inteiro potencia;
        inteiro i;

        escreva ("Digite o valor A: ");
        leia (a);

        escreva ("Digite o valor B: ");
        leia (b);

        // Verificar se b é positivo;
        se (b < 0) {
            escreva("Erro: B deve ser um número inteiro e positivo.")
        }
        senao {
            r <- 1
            potencia <- a
        }
            // Calcular a potência de a elevado a b
            para (i de 1 ate b) faca {
                r <- r * potencia
            }

            escreva("O resultado de ", a, " elevado a ", b, " é: ", r)
        
    }
}

**Comment by VanHai8** [comment]
programa {
inclua biblioteca Matematica --> mat
funcao inicio() {
inteiro a
inteiro b
inteiro r
inteiro potencia
inteiro i

    escreva ("Digite o valor A: ")
    leia(a)

    escreva ("Digite o valor B: ")
    leia(b)

    // Verificar se b é positivo;
    se (b < 0) {
        escreva("Erro: B deve ser um número inteiro e positivo.")
    }
    senao {
        r = 1
        potencia = a
        escreva("Pode prosseguir!")
    }
    potencia = mat.potencia(a, b)
        // Calcular a potência de a elevado a b
            r = r * potencia
        

        escreva("O resultado de ", a, " elevado a ", b, " é: ", r)
}
}

Tá na mão

**Comment by dgadelha** [comment]
Olá! Esse formato de código (atribuição com `<-`) indica o Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
