### ISSUE TITLE
 Estou escrevendo esse código para um projeto pessoal, o projeto consiste em um código para arredondar dado d6  para um d3 (RPG de mesa), mas está dando um erro na minha estrutura "se", na linha 18.

### ISSUE THREAD

**Issue by LTowww** [dgadelha/Portugol-Webstudio#156]
![erroportugol](https://github.com/dgadelha/Portugol-Webstudio/assets/158980945/18960da2-8dd3-4396-88f2-2e1555873ebf)

programa
{
	
	funcao inicio()
	{
		inteiro valord6, dadoarredondado
		
		escreva("--------------------------------------")
	   	escreva("\n-------------d3 VIRTUAL---------------")
	  	escreva("\n--------------------------------------")

	  	escreva("\nPrecisa de algo para arredondar o seu d6 para um d3 ?")
	  	escreva("\nInsira o valor que voce tirou no seu d6 aqui, que iremos arredondar para voce!!!\n")

	  	escreva("Insira o valor do seu d6 (1 a 6): ")
	  	leia(valord6)

		se(valord6 = "1"){
			dadoarredondado = 1
		}
		se(valord6 = "2"){
			dadoarredondado = 1
		}
		se(valord6 = "3"){
			dadoarredondado = 2
		}
		se(valord6 = "4"){
			dadoarredondado = 2 
		}
		se(valord6 = "5"){
			dadoarredondado = 3
		}
		se(valord6 = "6"){
			dadoarredondado = 3
		}

		escreva("O valor do d3 é: "+dadoarredondado)
	  	
	}
}

**Comment by justzackkkj** [comment]
aqui está o código corrigido, o erro está ocorrendo pois com apenas um = você está definindo o valor a variável, e não a comparando. Para fazer a comparação são necessários dois =

resumindo 
dar valor a variável: =
comparar o valor da variável com algum outro valor: == 

`programa{
  funcao inicio()
{
	inteiro valord6, dadoarredondado
	
	escreva("--------------------------------------")
   	escreva("\n-------------d3 VIRTUAL---------------")
  	escreva("\n--------------------------------------")

  	escreva("\nPrecisa de algo para arredondar o seu d6 para um d3 ?")
  	escreva("\nInsira o valor que voce tirou no seu d6 aqui, que iremos arredondar para voce!!!\n")

  	escreva("Insira o valor do seu d6 (1 a 6): ")
  	leia(valord6)

    se(valord6 == "1")
    {
      dadoarredondado = 1
    }
    senao se(valord6 == "2"){
      dadoarredondado = 1
    }
    se(valord6 == "3"){
      dadoarredondado = 2
    }
    se(valord6 == "4"){
      dadoarredondado = 2 
    }
    se(valord6 == "5"){
      dadoarredondado = 3
    }
    se(valord6 == "6"){
      dadoarredondado = 3
    }

	escreva("O valor do d3 é: "+dadoarredondado)
  	
}
}
`

**Comment by LTowww** [comment]
okk, obrigado!
