### ISSUE TITLE
Integrar analytcs do PS Web com o PS desktop

### ISSUE THREAD

**Issue by AlissonSteffens** [dgadelha/Portugol-Webstudio#16]
Como vcs devem ter visto (@guiscaranse até deu umas ideias lá) inseri uma funcionalidade que permite saber quantos users estão online no PotugolStudio. (em breve dados anônimos sobre a interface)
O que acham de integrar com o Portugol WebStudio? dai conseguimos ter dados mais interessantes sobre os usuários em geral?

**Comment by dgadelha** [comment]
Bora

**Comment by guiscaranse** [comment]
Tecnicamente a gente já coleta dados anônimos dos usuários usando o Google Analytics, que inclusive mostra quantos usuários estão online no momento.
Então não sei como se daria essa integração usando a plataforma de vocês.

**Comment by AlissonSteffens** [comment]
falei com o @dgadelha , acho que o ideal é vcs mandarem umas requests para o nosso serviço em alguns momentos específicos, Mais para termos dados globalizados da ferramenta, provavelmente seria um post quando a pessoa acessa o site e um put quando ela sai. a questão principal é: como fazer isso?

Acho que daria de ter um cookie ou algo assim que validasse seção, mas não sei ainda qual a melhor forma

**Comment by guiscaranse** [comment]
Nós validamos a entrada e saída dos usuários utilizando o socket.io no momento. É só implementar o código lá.
Segue o código a ser editado:
[Entrada do usuário](https://github.com/dgadelha/Portugol-Webstudio/blob/master/sockets/base.js#L5-L9)
[Saída do usuário](https://github.com/dgadelha/Portugol-Webstudio/blob/master/sockets/base.js#L81-L89)

**Comment by AlissonSteffens** [comment]
vou tentar deixar algo pronto esta semana 😄

**Comment by dgadelha** [comment]
@AlissonSteffens se isso ainda for rolar é só reabrir pra vermos como vai fazer ^^
