### ISSUE TITLE
Olá, gostari saber se tem a opção de tirar o corretor, pois é muito chato!

### ISSUE THREAD

**Issue by Wemersonsiqueira7** [dgadelha/Portugol-Webstudio#161]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

```

```

## Código:

Cole abaixo o seu código que está dando problema, caso seja problema com código.

```portugol
programa {

}
```

**Comment by Wemersonsiqueira7** [comment]
Tem como tirar o corretor?

**Comment by dgadelha** [comment]
Olá. Imagino que esteja falando sobre o corretor do Android, nesse caso, sugiro usar um teclado diferente: [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)
