### ISSUE TITLE
boa tarde galera estou com um erro de compilação

### ISSUE THREAD

**Issue by Vsnobre** [dgadelha/Portugol-Webstudio#163]
programa
	
	funcao inicio()
	{
	  inteiro base,reultado,expoente,contador	
		 
		 //solicita que o usuário informe a base e o espoente
		escreva("informe  a base: ")
		leia(base)
		escreva("informe  o expoente: ")
		leia(expoente)

		//verifica se a  base e o expoente são números inteiros e positivos
		se (base >= 0 e expoente >=0 então)
    
		    
		    //inicializa o resultado como 1
		    resultado := 1

		    // inicializa o contador
		    contador:= 1

		    //execulta o loop enquanto o contador for menor ou igual ao expoente
		    enquanto contador <= expoente faca
		    
		    //multiplica o resultado pela base
		    resultado := resultado * Base
		    //incrementa o contador
		    contador := contador +1
		    
		    fimenquanto

		    //exibe o resultado da potenciação
		    escreva(" o resultado de ", Base," elevado a ", Expoente," é: ", Resultado)
		senao

		       //exibe uma mensagem de erro se a base ou o expoente não forem inteiros e positivos
		        escreva("A base e o expoente devem ser números inteiros e positivos.")
         fimse
   fimalgoritmo      
		
		}

**Comment by dgadelha** [comment]
Olá! Essas palavras-chave (`fimenquanto`, `fimse`, `fimalgoritmo`) indicam o Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
