### ISSUE TITLE
O que esta acontecendo?

### ISSUE THREAD

**Issue by luizcardados** [dgadelha/Portugol-Webstudio#165]
programa {
  funcao inicio() {
    real n1, n2, media // declaração de Variaveis
    Escreva("Enter grade 1: ")
    Leia(n1)
    Escreva ("Enter grade 2: ")
    Leia(n2)
    media = (n1 + n2) / 2
    Se (media >= 7) {
      Escreva("Aluno Aprovado")
    } Senao {
      Escreva("Aluno Reprovado")
    }
  }
}

**Comment by dgadelha** [comment]
O problema é que as funções estão começando em maiúsculo
