### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by aalmeida19721** [dgadelha/Portugol-Webstudio#166]
programa {
  funcao inicio() {
    funcao biblioteca util
    inteiroV[10], temp{
    para(inteiro i=0;i<10;i++){
      V[i]=util.sorteia(1,10)
  
  }
    escreva(V)
    para(inteiro)i=10;i<9;i++){
      para(inteiro j=0;j<10;j++){
        se(v[j<V][i]){
          //troca
          temp=V[i]
          V[i]=V[j]
          V[j]=temp
        }
      }
      escreva("\n")
      escreva(V)
    }          
}

**Comment by dgadelha** [comment]
Olá! Este código parece estar em Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
