### ISSUE TITLE
Erro no procedimento

### ISSUE THREAD

**Issue by andressa-mb** [dgadelha/Portugol-Webstudio#171]
Estou chamando a funcao e dá erro onde eu declaro ela, sendo que é um procedimento não tenho que informar se é um inteiro ou não. 

```portugol
funcao cadastrarHospedes() {
      faca{
        escreva("Pode cadastrar. Digite o nome do hóspede: \n")
        leia(hospede)
        escreva("Digite o cpf: \n")
        leia(cpf)
        escreva("Digite a quantidade de dias hospedados: \n")
        leia(diasHosp)
        escreva("--RESUMO DAS INFORMAÇÕES--")
        escreva("Índice: ", indiceHospede, "\n")
        escreva("Nome: ", hospede, "\n")
        escreva("CPF: ", cpf, "\n")
        escreva("Quantidade de dias: ", diasHosp, "\n")
        escreva("Confirma as informações? S/N")
        leia(resposta)
        se(resposta == 'S'){
          escreva("Cadastro realizado com sucesso")
          indiceHospede++
        }senao {
          escreva("Favor cadastrar novamente")
          cadastrarHospedes()
        }       
        
      }
      enquanto(indiceHospede<10)
    }
```

**Comment by andressa-mb** [comment]
código completo, erro na funcao cadastrarHospedes(): 
programa {
  funcao inicio() {
    caracter resposta
    cadeia hospede, cpf
    inteiro opcao, indiceHospede = 0, diasHosp
    
    faca {
      escreva("-----MENU-----\n")
      escreva("1- Cadastrar hóspedes \n")
      escreva("2- Exibir hóspedes cadastrados \n")
      escreva("3- Reservar área de lazer \n")
      escreva("4- Calcular total à pagar \n")
      escreva("0- Sair \n")
      escreva("Digite o número da opção desejada: \n")
      leia(opcao)

      escolha(opcao){
        caso 0:
        sair()
        pare

        caso 1:
        cadastrarHospedes()
        pare

        caso 2: 
        exibirHospedes()
        pare

        caso 3:
        reservar()
        pare

        caso 4:
        totalPagar()
        pare

        caso contrario:
        escreva("Opção inválida")
      }

      enquanto(opcao!=0)

    funcao cadastrarHospedes() {
      faca{
        escreva("Pode cadastrar. Digite o nome do hóspede: \n")
        leia(hospede)
        escreva("Digite o cpf: \n")
        leia(cpf)
        escreva("Digite a quantidade de dias hospedados: \n")
        leia(diasHosp)
        escreva("--RESUMO DAS INFORMAÇÕES--")
        escreva("Índice: ", indiceHospede, "\n")
        escreva("Nome: ", hospede, "\n")
        escreva("CPF: ", cpf, "\n")
        escreva("Quantidade de dias: ", diasHosp, "\n")
        escreva("Confirma as informações? S/N")
        leia(resposta)
        se(resposta == 'S'){
          escreva("Cadastro realizado com sucesso")
          indiceHospede++
        }senao {
          escreva("Favor cadastrar novamente")
          cadastrarHospedes()
        }       
        
      }
      enquanto(indiceHospede<10)
    }

    funcao exibirHospedes() {
escreva("Até a próxima \n")
    }

    funcao reservar() {
escreva("Até a próxima \n")
    }

    funcao totalPagar() {
escreva("Até a próxima \n")
    }

    funcao sair() {
      escreva("Até a próxima \n")
    }

    }
  }
}

**Comment by dgadelha** [comment]
As funções precisam ser declaradas no escopo do programa, uma função não pode declarar outra função dentro de si mesma
