### ISSUE TITLE
Fala que possui um erro na linha 32, posição 8, porem não consigo resolver, podem me ajudar?

### ISSUE THREAD

**Issue by ArthurLDSS** [dgadelha/Portugol-Webstudio#172]
programa 
{
  funcao inicio() 
  {

    inteiro x, y, z, c, l

    x <- 0
    y <- 1
    l <- 15

    escreva("Esses são os 15 primeiros números da sequência de fibonacci: ")
    escreva(x)
    escreva(y)

    faca
    {

      z <- x + y
      escreva(z)
      x <- y
      y <- z
      l <- l - 1
      
    } enquanto (l > 2)

    escreva("\n")
    escreva("\n")
    escreva("Deseja continuar a contagem? (S/N): ")
    leia(c)

    se ((c ='S') ou (c ='s'))
    {

    escreva("\n")
    escreva("Digite até qual número gostaria de continuar a contar: ")
    leia(l)

    x <- 0
    y <- 1

      enquanto l > 0 faca
      {

       z <- x + y
       escreva(z)
       y <- z
        l <- l - 1

      }

    }
    senao
    {

      escreva("Ok irei para por aqui")

    }
  }
}

**Comment by dgadelha** [comment]
Olá! Utilizar `<-` para atribuição ao invés de `=` indica o Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
