### ISSUE TITLE
none

### ISSUE THREAD

**Issue by daniloanders** [dgadelha/Portugol-Webstudio#179]
programa {
  funcao inicio() {
  real A, B, SOMA
  escreva(A SOMA B = X) 
  leia (A SOMA B = X)
  escreva (X)
  }
}

**Comment by vitsssss** [comment]
![port](https://github.com/dgadelha/Portugol-Webstudio/assets/162717536/4b9b0fc5-75ba-40f7-85d3-08b53959e66f)
