### ISSUE TITLE
portugal

### ISSUE THREAD

**Issue by gus-45** [dgadelha/Portugol-Webstudio#180]
programa {
  funcao inicio() {
    inteiro numero1, subtracao1, subtracao2, subtracao3, subtracao4
    escreva("digite um numero:")
    leia(numero1)

    subtracao1 = numero1 - 4%
    subtracao2 = numero1 - 6%
    subtracao3 = numero1 - 40%
    subtracao4 = numero4 - 50%
    

    escreva("o resultado de votos brancos é:", subtracao1)
    escreva("o resultado de votos nulos é:", subtracao2)
    escreva("o resultado do candidato1 é:", subtracao3)
    escreva("o resultado do candidato2 é:", subtracao4)
  
  }
}

**Comment by lucasoliveirasfd** [comment]
Fala gus, beleza ? Então, consegui corrigir o problema no seu programa. Primeiramente, o tipo de variável não é inteiro e sim real. Após essa troca, o outro passo a se seguir é transformar essas porcentagens em numero decimais, sem esquecer do ponto ao invés da virgula. Ex: (4% = 0.04).
E manter a ordem de escrita certa... a cada comando "escreva" coloque a "subtração". 
Dessa forma:
![image](https://github.com/dgadelha/Portugol-Webstudio/assets/162715785/5a621f86-c241-4a5e-ad55-711d159d87e9)
