### ISSUE TITLE
⚠️ Durante essa fase experimental, o código ainda será executado mesmo com erros, porém se não corrigi-los, a execução abaixo pode exibir mensagens de erro em inglês ou sem explicação.    Caso acredite que o erro não faça sentido, por favor, abra uma issue em https://github.com/dgadelha/Portugol-Webstudio/issues/new e anexe o código que você está tentando executar.  - O seu programa irá iniciar abaixo -  ⛔ O seu código possui um erro de compilação!

### ISSUE THREAD

**Issue by aalmeida1972** [dgadelha/Portugol-Webstudio#182]
programa {
  inclua biblioteca Util
  funcao inicio() {
    //Exercicio 1
    inteiro matriz_ex1[5][5]
    inteiro soma_diag_esq=0
    inteiro soma_diag_dir=0

    //prenchendo a matriz entre 10 e 20

    para(inteiro i=0;i<5;i++){
      para(inteiro j=0;j<5;j++){
        matriz_ex1[i][j] = Util.sorteia(10,20)
        se(i==j) {
          soma_diag_esq = soma_diag_esq + matriz_ex1[i][j]

        se(i+j == 4) {
          soma_diag_dir = soma_diag_dir +matriz_ex1[i][j]
    
  }
       //Mostrando os elementos da diagonal esquerda e da diagonal direita
       escreva(Elementos da diagonal esquerda)
       para(inteiro i=0;i<5;i++){
        escreva(matriz_ex1[i][i]," ")
      }
      escreva("\nSoma dos elementos da diagonal esquerda\n",soma_diag_esq)

      escreva("\nElementos da diagonal direita:")
      para(inteiro)
}
  }
    }
  }
}

**Comment by dgadelha** [comment]
Olá, você esqueceu das aspas na função escreva ao exibir o texto

**Comment by aalmeida1972** [comment]
Obrigado Douglas. Pura distração.

Alexandre Almeida

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
