### ISSUE TITLE
codigo portugol 

### ISSUE THREAD

**Issue by AlexsandroLS** [dgadelha/Portugol-Webstudio#184]
programa {Exercicio
        var N1, N2, N3, N4, M: real 
  funcao inicio() {
    Escreva ('Programa que exibe a media da soma.')
    Escreva ('Digite um valor :') Leia (N1)
    Escreva ('Digite outro valor :') Leia (N2)
    Escreva ('Digite outro valor:') Leia (N3)
    Escreva ('Digite outro valor :') Leia (N4)
M <- (N1 + N2 + N3 + N4) / 4
Escreva ('O resultado da media da soma e:', M)
fim  }
}

**Comment by AlexsandroLS** [comment]
programa {Exercicio
        var N1, N2, N3, N4, M: real 
  funcao inicio() {
    Escreva ('Programa que exibe a media da soma.')
    Escreva ('Digite um valor :') Leia (N1)
    Escreva ('Digite outro valor :') Leia (N2)
    Escreva ('Digite outro valor:') Leia (N3)
    Escreva ('Digite outro valor :') Leia (N4)
M = (N1 + N2 + N3 + N4) / 4
Escreva ('O resultado da media da soma e:', M)
fim }

}

**Comment by cauaqz22** [comment]
![Anotação 2024-03-08 111916](https://github.com/dgadelha/Portugol-Webstudio/assets/162718624/a40e2c2d-c057-498e-a2fb-e2b198bf84c4)
