### ISSUE TITLE
Mensagem de erro no código

### ISSUE THREAD

**Issue by Evanio2020** [dgadelha/Portugol-Webstudio#187]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

mensagem de erro porém o código é executado.

```

## Código:

Cole abaixo o seu código que está dando problema, caso seja problema com código.
programa {
   funcao inicio() {
     inteiro num
  escreva("Digite um numero")
  leia(num)
    para (inteiro i=2; i<20; i=i*num){
      escreva (i, "\n")
    } 
  }
}

```portugol
programa {

}
```

**Comment by aquila0101** [comment]
o código correto fica assim:

programa {
   funcao inicio() {
     inteiro num
  escreva("Digite um numero: ")
  leia(num)
    para (inteiro i=2; i<20; i=i*num)
      escreva (i, "\n")
     
  
}
}
