### ISSUE TITLE
ajuda

### ISSUE THREAD

**Issue by joaomenorpecinha** [dgadelha/Portugol-Webstudio#188]
## Descrição do Problema: diz que o ínicio não foi declarado

Digite abaixo (entre os acentos) o que está acontecendo.

``` código não funciona

```

## Código: programa {}
funcao inicio () {
     

    algoritmo verificarSenha

    senha: caractere[5]
    senhaValida: caractere[5] = "asdfg"
    valido: logico
{
 inicio
    // Entrada de dados
    escreva("Digite a senha: ")
    leia(senha)
    
    // Verificar senha digitada
    se senha = senhaValida entao
        valido <- verdadeiro
    senao
        valido <- falso
    
    // Exibindo o resultado
    se valido entao
        escreva("Senha válida.")
    senao
        escreva("Senha inválida.")
    

    
  }
}

Cole abaixo o seu código que está dando problema, caso seja problema com código.

funcao inicio () {

**Comment by dgadelha** [comment]
Olá! Utilizar `<-` para atribuição ao invés de `=` indica o Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
