### ISSUE TITLE
nn sei

### ISSUE THREAD

**Issue by Ravenna-maker** [dgadelha/Portugol-Webstudio#190]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

```

```

## Código:

Cole abaixo o seu código que está dando problema, caso seja problema com código.

```portugol
programa {
  funcao inicio() {
    real n2,n2,n3
    escreva("Digite um número: ")
    leia(n1)
    
    escreva("Digite outro número: ")
    leia(n2)

    n3 = n1 + n2

    escreva("A soma dos dois números é: ",n3)
  }
}

```

**Comment by aquila0101** [comment]
você colocou o n2 repetido e não declarou o n1 o correto fica assim:

programa 
{
  
  
  funcao inicio() {
    real n1, n2, n3
    escreva("Digite um número: ")
    leia(n1)
    
    escreva("Digite outro número: ")
    leia(n2)

    n3 = n1 + n2

    escreva("A soma dos dois números é: ", n3)

  
  }
}
