### ISSUE TITLE
Erro de compilação

### ISSUE THREAD

**Issue by JessicaPMGomes** [dgadelha/Portugol-Webstudio#191]
Olá, ao declarar as variáveis da aula 11 Atribuição de variáveis : 
programa {
  funcao inicio() {
             cadeia sobrenome //declarando a variavel
             caracter nome
             sobrenome = "Gomes" //atribuindo valor a variavel
             nome = "R"
             escreva(sobrenome) //mostrando o valor da variavel
             escreva(nome)
  }
}
 Apresenta o seguinte erro : 
 
 ⛔ O seu código possui 1 erro de compilação:
   - Não é possível atribuir um valor do tipo 'cadeia' a uma variável do tipo 'caracter' (linha 6, posição 13) @dgadelha

**Comment by Esteveees** [comment]
Fala mano, tranquilo? Então, o erro ocorre porquê quando você define nome como caractere, ele identifica uma letra só, (R, como você definiu) e nesses casos, não é necessário aspas dupla ("), você define caractere com aspas simples (') segue o código funcionando:
programa {
funcao inicio() {
cadeia sobrenome //declarando a variavel
caracter nome
sobrenome = "Gomes " //atribuindo valor a variavel
nome = 'R'
escreva(sobrenome) //mostrando o valor da variavel
escreva(nome)
}
}

OBS: Está trocado porquê você pediu para que o sobrenome fosse escrito antes do nome.
