### ISSUE TITLE
somador

### ISSUE THREAD

**Issue by aoliver0** [dgadelha/Portugol-Webstudio#193]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

```
/*Aqui temos o cálculo da média que faz uso da função que chamamos de somador.*/
	    media = somador(valor1, valor2) / 2
```

## Código: 

funçao somador nao consta como declarada

Cole abaixo o seu código que está dando problema, caso seja problema com código.

```portugol
programa {
media = somador(valor1, valor2) / 2
}
```

**Comment by Esteveees** [comment]
Fala mano, segue explicação:
No seu programa, você só cita que a média é igual a soma dos valores dividido por dois, porém você fez errado!
Primeiro você deve pedir ao usuário o primeiro e o segundo valor, logo após isso, você deve declarar que o somador é igual ao valor1+valor2, e que a média é igual a somador dividido por dois, entendeu? vou por o código abaixo:
programa {
	
	funcao inicio()
	{ real media,somador,valor1,valor2
	escreva("Digite um número: ")
	leia(valor1)
	escreva("Digite um outro número: ")
	leia(valor2)
	somador = valor1+valor2
media = somador/2
escreva("A média entre ",valor1," e ",valor2," é: ",media)
}
}


OBS: Se você quiser que o resultado apareça na tela de forma detalhada, só fazer o que fiz na ultima linha, caso não tenha entendido, só entrar em contato comigo que eu te ajudo no que for preciso, fechou? :D

![github](https://github.com/dgadelha/Portugol-Webstudio/assets/162714698/8b2b29bd-959b-4c0c-9bcf-99b7d3b590eb)
