### ISSUE TITLE
AJUDA Para resolver

### ISSUE THREAD

**Issue by GoodyDSK** [dgadelha/Portugol-Webstudio#194]
## Descrição do Problema: erro de compilação
Função não declarada: media (linha 21, posição 4)

Digite abaixo (entre os acentos) o que está acontecendo.

```O seu código possui 1 erro de compilação:
  
```- Função não declarada: media (linha 21, posição 4)

## Código:

Cole abaixo o seu código que está dando problema, caso seja problema com código.

```portugol
programa {
    funcao real media(real n1, real n2, real n3) {
    real valorTotal = (n1 + n2 + n3) / 3
    retorne valorTotal
  }

  funcao inicio() {
    real n1, n2, n3, valorFinal
    para(inteiro i = 1; i <= 3; i++) {
      escreva("Digite o numero da posição ", i , " :")
      se(i == 1){
        leia(n1)
      }
      se(i == 2){
        leia(n2)
      }
      se(i == 3){
        leia(n3)
      }
    }
    valorFinal = media(n1, n2, n3)
    escreva("Media final: ", valorFinal)
    
   }

}
```

**Comment by Esteveees** [comment]
Fala mano, resolvi para você, segue explicação:
- Mudei a forma na qual você declarou as variáveis
- Retirei as variáveis valortotal e valorfinal, porquê todos tinham a mesma finalidade, fazer uma média.
- No fim, declarei que média era igual aos 3 números somados e divididos por três (quantidade), agora sim funciona.
programa {
    real media,n1,n2,n3 

  funcao inicio() {
    para(inteiro i = 1; i <= 3; i++) {
      escreva("Digite o numero da posição ", i , " : ")
      se(i == 1){
        leia(n1)
      }
      se(i == 2){
        leia(n2)
      }
      se(i == 3){
        leia(n3)
      }
    }
    media = (n1+n2+n3)/3
    escreva("Media final: ", media)
    
   }

}
![Uploading Problema solucionado.png…]()
