### ISSUE TITLE
Declaração de 'funcao' com retorno

### ISSUE THREAD

**Issue by MarcusAlindor** [dgadelha/Portugol-Webstudio#196]
## Descrição do Problema: Erro de compilação

Digite abaixo (entre os acentos) o que está acontecendo.

```
Bom o programa está funcionando e consegui o resultado que queria com esse teste de algoritimo, pórem o portugol informa que há um erro de compilação no código e não consigo interpretar qual seja o erro e qual sua solução.
```

## Código:

```portugol
programa{
  funcao parouimpar(inteiro v){
    se(v % 2 == 0){
      retorne "Par"
    }
      retorne "Impar"
  }

  funcao  inicio(){ 
    inteiro n
    cadeia r

    escreva("Digite um numero: ")
    leia(n)
    
    r = parouimpar(n)

    escreva("O numero ", n," é um valor ", r , "\n")
  }
}
```

**Comment by Esteveees** [comment]
Fala irmão, tudo certo? O seu código acabou ficando meio confuso e eu refiz ele, segui a sua lógica, porém fiz de um outro jeito, com menos linhas e mais claro, segue o código e a imagem dele funcionando:
![resolucao par ou impar](https://github.com/dgadelha/Portugol-Webstudio/assets/162714698/26adae31-b9f7-4ec2-be17-ee2eca3bf286)
- CÓDIGO DA IMAGEM:

programa{
	inteiro n
funcao inicio(){
escreva("Digite um numero: ")
leia(n)
se(n%2 == 0){
	escreva("O numero ",n," é par.\n")
}
senao{
	escreva("O número ",n," é impar.")
}
}
}
