### ISSUE TITLE
Strings com espaço não estão sendo passadas inteiras

### ISSUE THREAD

**Issue by guiscaranse** [dgadelha/Portugol-Webstudio#20]
Recentemente notei que quando você inserir strings com espaço (Ex:. "Seu João"), apenas a primeira metade da string será passada.
Eu não tenho certeza se isso é um problema no core que usamos ou no Webstudio. @dgadelha teria como você testar no core que você esta trabalhando?

Código para teste:
```
programa
{
	funcao inicio ()
	{
		cadeia nome

		escreva("Digite seu nome: ")
		leia(nome)
		escreva(nome)
	}
}
```
Resultado:
![capturar](https://user-images.githubusercontent.com/4432205/38418843-6eb7a61e-3974-11e8-8dd7-3562449eeadb.PNG)

**Comment by AlissonSteffens** [comment]
no core funciona normal; deseque seja passado como parâmetro entre aspas "Seu João";

**Comment by AlissonSteffens** [comment]
TEstei;
```
programa {
	funcao inicio() {
		cadeia a[5]
		para(inteiro i=0;i<5;i++){
		    escreva("entrada "+i)
		    leia(a[i])
		}
		para(inteiro i=0;i<5;i++){
		    escreva("\n"+i+" - "+a[i])
		}
	}
}

```
escreva nomes com espaço que o nome ocupará duas posições do vetor;
aparentemente é o problema que eu disse ali em cima mesmo 👍

**Comment by guiscaranse** [comment]
@AlissonSteffens tu tentou no core mais recente? O que eu to me referindo é [este aqui](https://github.com/UNIVALI-LITE-BACKUP/Portugol-Nucleo)
