### ISSUE TITLE
ordenar 5 valores

### ISSUE THREAD

**Issue by luublackstar** [dgadelha/Portugol-Webstudio#204]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

```
não esta ordenando os números
```

## Código:

Cole abaixo o seu código que está dando problema, caso seja problema com código.

```portugol
programa {

  inteiro  valor1, valor2, valor3, valor4, valor5 
  inteiro maior, menor 


    escreva("Digite o valor 1: ")
    leia(valor1)

    escreva("Digite o valor 2: ")
    leia(valor2)

    escreva("Digite o valor 3: ")
    leia(valor3)

    escreva("Digite o valor 4: ")
    leia(valor4)

    escreva("Digite o valor 5: ")
    leia(valor5)

    
    maior <- valor1
    Se (valor2 > maior ou maior <- valor2)
    
    Se (valor3 > maior ou maior <- valor3)
    
    Se (valor4 > maior ou maior <- valor4)
    
    Se (valor5 > maior ou  maior <- valor5)
    

    
    menor <- valor1
    Se (valor2 < menor ou menor <- valor2)
    
    Se (valor3 < menor ou menor <- valor3)
    
    Se (valor4 < menor ou  menor <- valor4)
    
    Se (valor5 < menor
 ou menor <- valor5)
    

    escreva("O maior valor informado é: ", maior)
    escreva("O menor valor informado é: ", menor)


}
```

**Comment by Esteveees** [comment]
Opa mano, consegui solucionar o seu problema, segue o código e a imagem com tudo funcionando, segue explicação:
- Você declarou que "MAIOR" recebe "valor1", mas utilizou "<-", isso funciona somente no visualg, no caso do portugol, você tem que utilizar "=".
- No caso do se, utilize com "s" minúsculo, se não dará conflito, além disso, utilize chaves "{" após o "se" e a condição.
- Você se esqueceu de declarar a função no começo do programa.
-`programa {

  inteiro  valor1,valor2,valor3,valor4,valor5 
  inteiro maior,menor 
  funcao inicio(){
    escreva("Digite o valor 1: ")
    leia(valor1)

    escreva("Digite o valor 2: ")
    leia(valor2)

    escreva("Digite o valor 3: ")
    leia(valor3)

    escreva("Digite o valor 4: ")
    leia(valor4)

    escreva("Digite o valor 5: ")
    leia(valor5)

    
    maior = valor1
    se(maior<valor2){
    	maior = valor2
    }
    se(maior<valor3){
    	maior = valor3
    }
    
    se(maior<valor4){
    	maior = valor4
    }
    
    se(maior<valor5){
    	maior = valor5
    }
    

    
    menor = valor1
    se(menor>valor2){
    	menor = valor2
    }
    se(menor>valor3){
    	menor = valor3
    }
    
    se(menor>valor4){
    	menor = valor4
    }
    
    se(menor>valor5){
    	menor = valor5
    }
    

    escreva("O maior valor informado é: ",maior,".\n")
    escreva("O menor valor informado é: ",menor)


}
}`

**Comment by Esteveees** [comment]
Opa mano, consegui solucionar o seu problema, segue o código e a imagem com tudo funcionando, segue explicação:
- Você declarou que "MAIOR" recebe "valor1", mas utilizou "<-", isso funciona somente no visualg, no caso do portugol, você tem que utilizar "=".
- No caso do se, utilize com "s" minúsculo, se não dará conflito, além disso, utilize chaves "{" após o "se" e a condição.
- Você se esqueceu de declarar a função no começo do programa.

`
programa {

  inteiro  valor1,valor2,valor3,valor4,valor5 
  inteiro maior,menor 
  funcao inicio(){
    escreva("Digite o valor 1: ")
    leia(valor1)

    escreva("Digite o valor 2: ")
    leia(valor2)

    escreva("Digite o valor 3: ")
    leia(valor3)

    escreva("Digite o valor 4: ")
    leia(valor4)

    escreva("Digite o valor 5: ")
    leia(valor5)

    
    maior = valor1
    se(maior<valor2){
    	maior = valor2
    }
    se(maior<valor3){
    	maior = valor3
    }
    
    se(maior<valor4){
    	maior = valor4
    }
    
    se(maior<valor5){
    	maior = valor5
    }
    

    
    menor = valor1
    se(menor>valor2){
    	menor = valor2
    }
    se(menor>valor3){
    	menor = valor3
    }
    
    se(menor>valor4){
    	menor = valor4
    }
    
    se(menor>valor5){
    	menor = valor5
    }
    

    escreva("O maior valor informado é: ",maior,".\n")
    escreva("O menor valor informado é: ",menor)


}
}`

![github maior e menor](https://github.com/dgadelha/Portugol-Webstudio/assets/162714698/15be807c-4a4a-4997-919d-6922a7bf683b)

**Comment by Esteveees** [comment]
Opa mano, consegui solucionar o seu problema, segue o código e a imagem com tudo funcionando, segue explicação:
- Você declarou que "MAIOR" recebe "valor1", mas utilizou "<-", isso funciona somente no visualg, no caso do portugol, você tem que utilizar "=".
- No caso do se, utilize com "s" minúsculo, se não dará conflito, além disso, utilize chaves "{" após o "se" e a condição.
- Você se esqueceu de declarar a função no começo do programa.

```
programa {

  inteiro  valor1,valor2,valor3,valor4,valor5 
  inteiro maior,menor 
  funcao inicio(){
    escreva("Digite o valor 1: ")
    leia(valor1)

    escreva("Digite o valor 2: ")
    leia(valor2)

    escreva("Digite o valor 3: ")
    leia(valor3)

    escreva("Digite o valor 4: ")
    leia(valor4)

    escreva("Digite o valor 5: ")
    leia(valor5)

    
    maior = valor1
    se(maior<valor2){
    	maior = valor2
    }
    se(maior<valor3){
    	maior = valor3
    }
    
    se(maior<valor4){
    	maior = valor4
    }
    
    se(maior<valor5){
    	maior = valor5
    }
    

    
    menor = valor1
    se(menor>valor2){
    	menor = valor2
    }
    se(menor>valor3){
    	menor = valor3
    }
    
    se(menor>valor4){
    	menor = valor4
    }
    
    se(menor>valor5){
    	menor = valor5
    }
    

    escreva("O maior valor informado é: ",maior,".\n")
    escreva("O menor valor informado é: ",menor)


}
}
```

![maior e menor github](https://github.com/dgadelha/Portugol-Webstudio/assets/162714698/9bf1f644-f8f2-4bc7-9550-51f883f23c09)
