### ISSUE TITLE
Problema de executar código

### ISSUE THREAD

**Issue by Gust01002** [dgadelha/Portugol-Webstudio#205]
## Descrição do Problema:

Digite abaixo (entre os acentos) o que está acontecendo.

```
Está dando erro nas linhas de 3 a 9
```

## Código:

programa {
    funcao inicio() {
        ESCREVA "Pegar uma escada"
        ESCREVA "Posicionar a escada debaixo da lâmpada"
        ESCREVA "Buscar uma lâmpada reserva"
        ESCREVA "Retirar a lâmpada velha"
        ESCREVA "Colocar a lâmpada reserva"
    }
}

**Comment by dgadelha** [comment]
Olá! O código em Portugol precisa ter parênteses para chamar a função escreva.

Segue abaixo o código correto:

```portugol
programa {
  funcao inicio() {
    escreva("Pegar uma escada")
    escreva("Posicionar a escada debaixo da lâmpada")
    escreva("Buscar uma lâmpada reserva")
    escreva("Retirar a lâmpada velha")
    escreva("Colocar a lâmpada reserva")
  }
}
```
