### ISSUE TITLE
Atribuição do tamanho de um vetor por variavel nao funciona

### ISSUE THREAD

**Issue by NicollasLuz** [dgadelha/Portugol-Webstudio#211]
### Descrição do problema

Estou fazendo um trabalho de escola e estou tendo um problema onde a atribuição do tamanho de um vetor por variavel nao funciona, estou pedindo qual o tamanho do vetor para o usuario, porem pos isso o codigo nao funciona, mesmo inicializando o vetor apos o valor ser digitado

### Código

```portugol
programa {
  	inclua biblioteca Util

    inteiro quantidade_num = 0, tempo = 9999, tamanhoDificil = 0, tempoDificil, numPraChuta, tentativas = 0, numPraAcertar, timer, numParaAcertarDif[], numPraAcertar[]
    logico modoDificil

  funcao inicio() {
    escreva("Você quer jogar o modo difícil: \n")
    leia(modoDificil)

    se(modoDificil){
      tamanhoDificil = Util.sorteia(10, 20)
      tempoDificil = Util.sorteia(150, 200)
      //O erro está aqui pois nao aceita tamanhodifcil como tamanho do vetor. Mesmo se tirarmos de sorteio ele nao funciona com o valor sendo por variavel 
      inteiro numParaAcertarDif[tamanhoDificil] 

      para (inteiro i = 0; i < tamanhoDificil; i++) {
        numParaAcertarDif[i] = Util.sorteia(0, 25)
      }
    } senao{
    escreva("Qual a quantidade de números que você quer tentar acertar: ")
    leia(quantidade_num)
      //Aqui tambem ocorre o mesmo erro citado acima
      inteiro numPraAcertar[quantidade_num]

      para (inteiro u = 0; u < quantidade_num; u++) {
        numPraAcertar[u] = Util.sorteia(0, 25)
        escreva(numPraAcertar[u], " ")
      }
    
      se(quantidade_num == 1){
        def_tempo(30)
        acertar_numero()
      } senao se(quantidade_num >= 2 e quantidade_num <= 4){
        def_tempo(95)
      } senao se (quantidade_num >= 5 e quantidade_num <= 7){
        def_tempo(150)
      } senao se(quantidade_num >= 8 e quantidade_num <= 10){
        def_tempo(250)
      } senao se(quantidade_num >= 11){
        tempo_sabido()
      } senao se(quantidade_num <= 0){
        escreva("A quantidade de números é inválida")
      }
    }
  }

  funcao tempo_sabido(){
    escreva("\nTabela de tempo ")
    escreva("\n 1 número até 30 segundos")
    escreva("\n De 2 até 4 números até 95 segundos")
    escreva("\n De 5 até 7 números até 150 segundos")
    escreva("\n De 8 até 10 números até 250 segundos")
    escreva("\n Mais de 11 números tempo ilimitado")
    escreva("\nQual a quantidade de tempo que você quer: ")
    leia(tempo)
  }

  funcao def_tempo(inteiro a){
      enquanto(tempo > a){
        tempo_sabido()
          se(tempo > a){
            escreva("Tempo inválido para a quantidade de números, tente novamente!\n")
          } senao {
            escreva("Tempo definido com sucesso!\n")
          }
      }
  }

  funcao acertar_numero(){
    timer = Util.tempo_decorrido()
    para(inteiro j = 0; j != tempo; j++){
      escreva(timer)
      escreva("Qual número você vai tentar: ")
      leia(numPraChuta)
      se(numPraChuta == numPraAcertar[tentativas]){
        tentativas++
      } 
      se(tentativas == quantidade_num){
        j = tempo
      }
    }
  }
  funcao acertar_numero_dificil(){
    
    para(inteiro j = 0; j != tempoDificil; j++){

    }
  }
}
```

### Comentários adicionais

Nao sei se é erro de sintax ou erro da plataforma se alguem conseguir me ajudar ficarei grato!
Obrigado desde ja

um exemplo mais facil de entender seria 

programa {
  inteiro tamanho, num[]

  funcao inicio() {
    escreva("Qual o tamanho: ")
    leia(tamanho)
    
    num[tamanho]

    teste()

  }
  funcao teste(){
    escreva("Qual o n1: ")
    leia(num[0])
  }
}

**Comment by aquila0101** [comment]
Acho que deve ser por que você declarou numParaAcertarDif 2 vezes linha 15 e 4 e tamanhoDificil acho que deveria ser uma constante e quantidade_num tambem

**Comment by NicollasLuz** [comment]
> Acho que deve ser por que você declarou numParaAcertarDif 2 vezes linha 15 e 4 e tamanhoDificil acho que deveria ser uma constante e quantidade_num também

O problema também é que o portugol nao aceita vetores globais aqui esta um exemplo da mesma coisa de forma simplificada

```
programa {
inteiro tamanho, num[]

funcao inicio() {
escreva("Qual o tamanho: ")
leia(tamanho)

num[tamanho]

teste()
}
funcao teste(){
escreva("Qual o n1: ")
leia(num[0])
}
}

```
se voce tentar copiar e colar esse codigo ele da erro, pois o portugol nao vai aceitar a leitura da posição de uma casa se você estiver declarando o tamanho dela depois e nao na declaraçao inicial dela. Acho que ficou meio confuso de entender mas acho que o exemplo diz muito

**Comment by dgadelha** [comment]
Olá, eu não consegui reproduzir o problema aqui, nenhum dos códigos é válido no Portugol Studio (o app da UNIVALI)

Ao declarar um vetor, você precisa definir o tamanho dele através de um número inteiro ou uma constante do tipo inteiro, não sendo possível declarar com um tamanho a partir de uma variável

O erro exibido pelo Portugol Studio é o seguinte:

```
O tamanho do vetor 'nome' deve ser um valor ou uma constante do tipo inteiro e positivo Ex: vetor[3]
```

Como o Portugol Webstudio ainda possui um analisador semântico muito limitado, não implementei essa verificação, e pelo fato de o código final ser executado como JavaScript, é possível utilizar algo desse gênero aqui:

```portugol
programa {
  funcao inicio() {
    inteiro tamanho
    escreva("Tamanho: ")
    leia(tamanho)

    inteiro vetor[tamanho]

    teste(vetor)
  }

  funcao teste(inteiro vetor[]) {
    escreva("Qual o n1: ")
    leia(vetor[0])

    escreva(vetor[0])
  }
}
```

Obs.: essa sintaxe será removida em uma versão futura, quando as checagens do analisador semântico forem melhoradas

**Comment by NicollasLuz** [comment]
> Olá, eu não consegui reproduzir o problema aqui, nenhum dos códigos é válido no Portugol Studio (o app da UNIVALI)
> 
> Ao declarar um vetor, você precisa definir o tamanho dele através de um número inteiro ou uma constante do tipo inteiro, não sendo possível declarar com um tamanho a partir de uma variável
> 
> O erro exibido pelo Portugol Studio é o seguinte:
> 
> ```
> O tamanho do vetor 'nome' deve ser um valor ou uma constante do tipo inteiro e positivo Ex: vetor[3]
> ```
> 
> Como o Portugol Webstudio ainda possui um analisador semântico muito limitado, não implementei essa verificação, e pelo fato de o código final ser executado como JavaScript, é possível utilizar algo desse gênero aqui:
> 
> ```portugol
> programa {
>   funcao inicio() {
>     inteiro tamanho
>     escreva("Tamanho: ")
>     leia(tamanho)
> 
>     inteiro vetor[tamanho]
> 
>     teste(vetor)
>   }
> 
>   funcao teste(inteiro vetor[]) {
>     escreva("Qual o n1: ")
>     leia(vetor[0])
> 
>     escreva(vetor[0])
>   }
> }
> ```
> 
> Obs.: essa sintaxe será removida em uma versão futura, quando as checagens do analisador semântico forem melhoradas

Valeu mn, muito obrigado
