### ISSUE TITLE
Primeiras palavras do console estão sendo cortadas

### ISSUE THREAD

**Issue by Guilherm456** [dgadelha/Portugol-Webstudio#22]
Após colocar os comandos  de "escreva" para ser executado, as primeiras palavras são cortadas
Exemplo de um código que isso ocorre:
> programa {
    inteiro nascimento,atual,anos 
	funcao inicio() { 
		escreva("Qual é o ano do seu nascimento?")
		leia(nascimento) //Pergunta o ano de nascimento
		escreva ("Qual é o ano atual?")
		leia(atual) 
		anos= atual-nascimento
		escreva ("Você tem ",anos," anos")
	}
}

Resultado do console:
![Anotação 2019-03-12 180547](https://user-images.githubusercontent.com/18385445/54236211-d69e0c80-44f1-11e9-986e-5a09656a8f18.jpg)

**Comment by guiscaranse** [comment]
Olá @Guilherm456, consegui reproduzir sua issue aqui. Parece ser um erro no [editor.js](https://github.com/dgadelha/Portugol-Webstudio/blob/e4e796dac78186f7199577d262571a137c889ec6/public/assets/editor/editor.js#L87-L92). @dgadelha você pode dar uma olhada nisso?

**Comment by dgadelha** [comment]
Corrigido em https://github.com/dgadelha/Portugol-Webstudio/commit/74775aa84dd4ccc2bfd661f72400e32c3c0c9018, obrigado por reportar :)
