### ISSUE TITLE
Digite o nome do segundo filme: lll Digite o nome do terceiro filme: ççç Digite o nome do quarto filme: ppp Os seus filmes são: mNaNlNaNçNaNp Programa finalizado. Tempo de execução: 49723 milissegundos

### ISSUE THREAD

**Issue by LukaszZz00** [dgadelha/Portugol-Webstudio#230]
### Descrição do problema

Os seus filmes são: pNaNlNaNmNaNo
this is answers. it´s wrong

### Código

```portugol
programa {
  funcao inicio()
   {
    caracter filme1, filme2, filme3, filme4

    //Solicita ao usario que coloca o nome de 4 filmes
    escreva("Digite o nome do primeiro filme: ")
    leia(filme1)

    escreva("Digite o nome do segundo filme: ")
    leia(filme2)

    escreva("Digite o nome do terceiro filme: ")
    leia(filme3)

    escreva("Digite o nome do quarto filme: ")
    leia(filme4)
  

    //Escreva o nome dos filmes separados por virgulas
    escreva("Os seus filmes são: ", filme1, + ", " + filme2, + ", "  + filme3, + ", ", filme4)
```

### Comentários adicionais

there a error of code

**Comment by ronneyns** [comment]
O problema está na linha escreva, ao misturar o separador de parâmetros ("," - vírgula) com o operador de concatenação de cadeias ("+" - adição).
Veja este exemplos:
- `escreva("Os seus filmes são: ", filme1, ", ", filme2, ", ", filme3, ", ", filme4)`
- `escreva("Os seus filmes são: " + filme1 + ", " + filme2 + ", " + filme3 + ", " + filme4)`
- `escreva("Os seus filmes são: " + filme1, ", ", filme2 + ", ", filme3, ", " + filme4)`
