### ISSUE TITLE
Olá mundo

### ISSUE THREAD

**Issue by GBwolf1** [dgadelha/Portugol-Webstudio#240]
### Descrição do problema

![Captura de tela 2024-06-13 120523](https://github.com/dgadelha/Portugol-Webstudio/assets/169725954/3447e2ac-eb2b-4432-81f1-7f895a0a4291)
estou tentando fala olá, mundo mas não vai

### Código

```portugol
escreva('Ola, mundo!')
```

### Comentários adicionais

![Captura de tela 2024-06-13 120523](https://github.com/dgadelha/Portugol-Webstudio/assets/169725954/77f14f5a-7293-47b5-bd18-105ee6748009)

**Comment by dgadelha** [comment]
Olá,

O correto seria o uso de aspas duplas para indicar uma cadeia. O uso de aspas simples indica apenas um caractere.

Com aspas duplas (cadeia):

```portugol
programa {
  funcao inicio() {
    escreva("Olá, mundo!")
  }
}

```

Com aspas simples (caractere):

```portugol
programa {
  funcao inicio() {
    escreva('O')
    escreva('l')
    escreva('á')
    escreva(',')
    escreva(' ')
    escreva('m')
    escreva('u')
    escreva('n')
    escreva('d')
    escreva('o')
    escreva('!')
  }
}
```
