### ISSUE TITLE
Lesson about input a string and output a name you input.

### ISSUE THREAD

**Issue by AnthonyBastos** [dgadelha/Portugol-Webstudio#247]
### Descrição do problema

When using the example about string input, see in the lesson a mistake. The code only describes an input process and guards the string in a variable, not showing the name.

### Código

```portugol
/* CLIQUE NO SINAL DE "+", À ESQUERDA, PARA EXIBIR A DESCRIÇÃO DO EXEMPLO
 *  
 * Copyright (C) 2014 - UNIVALI - Universidade do Vale do Itajaí
 * 
 * Este arquivo de código fonte é livre para utilização, cópia e/ou modificação
 * desde que este cabeçalho, contendo os direitos autorais e a descrição do programa, 
 * seja mantido.
 * 
 * Se tiver dificuldade em compreender este exemplo, acesse as vídeoaulas do Portugol 
 * Studio para auxiliá-lo:
 * 
 * https://www.youtube.com/watch?v=K02TnB3IGnQ&list=PLb9yvNDCid3jQAEbNoPHtPR0SWwmRSM-t
 * 
 * Descrição:
 * 
 * 	Este exemplo utiliza a entrada de dados do Portugol para obter e armazenar 
 * 	o nome do usuário em um variável. Logo após, utiliza a saída de dados para
 *   exibir o nome digitado.
 * 
 * Autores:
 * 
 * 	Giordana Maria da Costa Valle
 * 	Carlos Alexandre Krueger
 * 	
 * Data: 01/06/2013
 */
 
programa
{
	funcao inicio ()
	{
		cadeia nome

		escreva("Digite seu nome: ")
		leia(nome)
	}
}
```

### Comentários adicionais

![image](https://github.com/dgadelha/Portugol-Webstudio/assets/173524614/6aaf2174-3d61-4ab0-9afc-810a445e277b)

**Comment by dgadelha** [comment]
Olá!

No momento, o Portugol Webstudio está utilizando toda a parte de Ajuda e Exemplos igual à do [Portugol Studio](https://univali-lite.github.io/Portugol-Studio/).

Infelizmente, os ajustes de exemplo, no momento, devem ser solicitados lá no GitHub deles: https://github.com/UNIVALI-LITE/Portugol-Studio/issues/new

Ainda estou avaliando a possibilidade de fazer um _fork_ desses exemplos e ajustá-los, mas não tenho tempo no momento.

**Comment by AnthonyBastos** [comment]
Boa noite, bom dia Douglas Gadelha, tudo bacana?
    Obrigado pelo suporte, podendo observar a questão dos 'Exemplos', de
tudo já é de bem homem.


Em qua., 24 de jul. de 2024, 22:57, Douglas Gadêlha <
***@***.***> escreveu:
