### ISSUE TITLE
sinal = não reconhecido

### ISSUE THREAD

**Issue by PY5VC** [dgadelha/Portugol-Webstudio#251]
### Descrição do problema

sinal = não funciona

### Código

```portugol
programa {
  funcao inicio() {
    inteiro valor1 
    
    /*contador=1*/
    
    escreva("Digite um valor: \n")
    leia(valor1)
para(inteiro x = 1; x = 10; x++){
//    para(inteiro x=1; x = 10; x+1){

      escreva(x, " - ")
    }
```

### Comentários adicionais

programa não reconhece o sinal =
![image](https://github.com/dgadelha/Portugol-Webstudio/assets/84381990/19aaa74a-069a-4ff8-8a68-85531f30e9ba)

**Comment by ronneyns** [comment]
Um sinal de igualdade "=" é usado para atribuir valores. Para testar a igualdade de valores, use "==".
Veja em:
- Ajuda -> Linguagem Portugol -> Expressões -> Operações Relacionais
- Ajuda -> Linguagem Portugol -> Expressões -> Atribuições
