### ISSUE TITLE
Não estou conseguindo identificar o erro nesse código

### ISSUE THREAD

**Issue by Gui119** [dgadelha/Portugol-Webstudio#264]
### Descrição do problema

Estou escrevendo o código igual na aula que eu estou fazendo e mesmo assim no meu da erro, e na do professor da certo.

### Código

```portugol
programa {
  funcao inicio() {
    inteiro numeroTab, termo, contador
    escreva("Olá, vamos determinar uma tabuada! \n")
    escreva("Digite o número para iniciarmos: \n")
    leia(numTab)
    escreva("O número que você digitou é ", numTab, ", ! \n")
  }
}
```

### Comentários adicionais

![Captura de tela 2024-08-03 171441](https://github.com/user-attachments/assets/2f2e4fac-b53d-4621-a35e-fa5be31fe3b2)

**Comment by dgadelha** [comment]
Olá,

O erro foi na referência a variável, você declarou como `numeroTab` e utilizou como `numTab`:

```portugol
programa {
  funcao inicio() {
    inteiro numeroTab, termo, contador
    escreva("Olá, vamos determinar uma tabuada! \n")
    escreva("Digite o número para iniciarmos: \n")
    leia(numeroTab)
    escreva("O número que você digitou é ", numeroTab, ", ! \n")
  }
}
```
