### ISSUE TITLE
Como resolver meu problema?

### ISSUE THREAD

**Issue by Mateus342** [dgadelha/Portugol-Webstudio#266]
### Descrição do problema

Ao fazer meu código está dizendo o seguinte problema: "Expressão inválida: <missing '('>"

<img width="858" alt="Captura de tela 2024-08-07 085732" src="https://github.com/user-attachments/assets/4975e04b-b4c9-4793-b806-bc2ec84bee38">

### Código

```portugol
programa {
  funcao inicio() {
    inteiro i, 1
    // Recebe os 10 números
      para i de 1 ate 10 faca
        escreva("Digite o ", i, "º número: ")
        leia(i)
    } 
    // Inicializa o menor número com o primeiro elemento do vetor
     menor = numeros[1]

    // Percorre o vetor para encontrar o menor número
     para i de 2 ate 10 faca
        se numeros[i] < menor 
            menor := numeros[i]
      }
    }

    // Exibe o menor número
     escreva("O menor número é: ", menor) 
  }
}
```

### Comentários adicionais

<img width="858" alt="Captura de tela 2024-08-07 085732" src="https://github.com/user-attachments/assets/8db216ac-3d47-48d0-a010-fbdc52d51b5f">

**Comment by BiancaFL** [comment]
![image](https://github.com/user-attachments/assets/a1d03b52-f143-4a6d-9fd9-fce016d87a2a)

Outros erros no código:
- Vetor de números não está definido
- Valor lido não está sendo salvo no vetor de números
- Não esquecer que o vetor começa na posição 0
