### ISSUE TITLE
Erro ao executar algoritmo

### ISSUE THREAD

**Issue by lcmuniz** [dgadelha/Portugol-Webstudio#27]
Quando se clica para executar o algoritmo (botão Play), o sistema não mostra nada. Nem a saída do algoritmo ou mensagem de erro. Os botões de executar e parar travam e o editor não deixa digitar nada.
No console do navegador aparece: O Firefox não conseguiu estabelecer uma conexão com o servidor wss://portugol-webstudio.dgadelha.xyz/socket.io/?EIO=3&transport=websocket&sid=u1ZvsO3EixXqIUYvAAXW.

**Comment by guiscaranse** [comment]
Olá @lcmuniz, é possível que o servidor tenha reiniciado durante a execução, você poderia tentar novamente e me dizer se o problema persiste?

**Comment by dgadelha** [comment]
O servidor estava com uma carga bastante alta por causa de uma atualização automática recente, resolvi o problema.

Adicionalmente, em breve devo terminar a migração de servidor, visando aumentar a qualidade da execução.
