### ISSUE TITLE
A floresta Sussurante

### ISSUE THREAD

**Issue by BSantos9711** [dgadelha/Portugol-Webstudio#270]
### Descrição do problema

ao tentar executar o código, um IDE exibe um erro de sintaxe ao função "escreva"

### Código

```portugol
escreva("3. Caminho das criaturas\n")
```

**Comment by BiancaFL** [comment]
Amigx, acredito que você não tenha consultado a documentação do Webstudio
O comando `programa` é obrigatório e você também precisa declarar um função `inicio`

Sendo assim, seu código ficaria:

```
programa{
  funcao inicio(){
    escreva("3. Caminho das criaturas\n")
  }
}
```

**Comment by Lavinor** [comment]
Olá, estou tentando desenvolver um programa em que tenho que declarar uma variável chamada "caminho", como posso criá-la? Abaixo vou escrever todo o meu algorítimo e mais abaixo, vou escrever a mensagem de erro, ok?
programa {
  funcao inicio()
  {
      inteiro opcao
      escreva("Você é um explorador corajoso que se aventura em uma misteriosa Floresta Sussurrante em busca de tesouros lendários e segredos perdidos.\n")
      escreva("Ao adentrar na floresta, você se depara com três caminhos diferentes:\n")
      escreva("1. O Caminho das Sombras\n")
      escreva("2. O Caminho da Luz\n")
      escreva("3. O Caminho das Criaturas")
      escreva("Escolha um caminho (1, 2 ou 3): ")
      leia(opcao)
      escolha(caminho)
      {
        caso 1:
          Caminhio_das_Sombras()
          pare
        caso 2:
          Caminho_da_Luz()
          pare
        caso 3:
          Caminho_das_Criaturas()
          pare
        caso contrario:
          escreva("Escolha inválida. Por favor selecione um caminho válido.\n")
          leia(caminho)
          escolher_caminho(caminho)
      } 
  }
}

Mensagem de erro:
⛔ O seu código possui 1 erro de compilação:
 - Variável não declarada: caminho (linha 12, posição 14)

**Comment by caiomikulski** [comment]
@Lavinor observando o seu código, você pode renomear a variável "opção" para a variável "caminho". Da forma que está seu código, você criou a variável "opção" porém na estrutura escolha, você inseriu a variável "caminho" que ainda não existe no seu programa pois você não a declarou.

```
programa {
funcao inicio()
{
inteiro caminho
escreva("Você é um explorador corajoso que se aventura em uma misteriosa Floresta Sussurrante em busca de tesouros lendários e segredos perdidos.\n")
escreva("Ao adentrar na floresta, você se depara com três caminhos diferentes:\n")
escreva("1. O Caminho das Sombras\n")
escreva("2. O Caminho da Luz\n")
escreva("3. O Caminho das Criaturas")
escreva("Escolha um caminho (1, 2 ou 3): ")
leia(caminho)
escolha(caminho)
{
caso 1:
escreva("Caminho_das_Sombras()")
pare
caso 2:
escreva("Caminho_da_Luz()")
pare
caso 3:
escreva("Caminho_das_Criaturas()")
pare
caso contrario:
escreva("Escolha inválida. Por favor selecione um caminho válido.\n")
}
}
}
```
