### ISSUE TITLE
calculo

### ISSUE THREAD

**Issue by luciano1323-web** [dgadelha/Portugol-Webstudio#271]
### Descrição do problema

e em portugol e não sei o motivo dele não ser executado

### Código

```portugol
programa
{}
  funcao inicio()
  {
 real num 1, num 2, soma
 num1 = 10
 num2 = 5
 soma= num1 + num2 // soma os dois valores
 escreva("\nA soma dos números é igual a: ",soma)
  }
```

**Comment by BiancaFL** [comment]
Vejo dois erros no seu código:

1º a sua função `inicio` está fora do escopo do programa
correção: mover para dentro do escopo

```
programa
{
     funcao inicio()
       {
            real num 1, num 2, soma
            num1 = 10
            num2 = 5
            soma= num1 + num2 // soma os dois valores
            escreva("\nA soma dos números é igual a: ",soma)
       }
}
```

2º não pode haver espaços no nome de variávies
mude `real num 1, num 2, soma` para `real num1, num2, soma`
