### ISSUE TITLE
Problema neste código. Randomico não existe

### ISSUE THREAD

**Issue by maristelaiopealcantara** [dgadelha/Portugol-Webstudio#279]
### Descrição do problema

Não consigo encontrar o erro.

### Código

```portugol
programa
{
    funcao inicio()
    {
        // Variáveis
        inteiro numero_secreto, palpite, tentativas

        // Gera um número aleatório entre 1 e 100
        numero_secreto = randomico(1, 100)
        tentativas = 0

        // Loop para o jogo de adivinhação
        enquanto (verdadeiro)
        {
            escreva("Digite o seu palpite (entre 1 e 100): ")
            leia(palpite)
            tentativas = tentativas + 1

            // Verifica se o palpite está correto
            se (palpite == numero_secreto)
            {
                escreva("Parabéns! Você acertou o número em ", tentativas, " tentativas.\n")
                pare // Sai do loop
            }
            senao se (palpite < numero_secreto)
            {
                escreva("O número secreto é maior.\n")
            }
            senao
            {
                escreva("O número secreto é menor.\n")
            }
        }
    }
}
```

**Comment by CaduDev2505** [comment]
Resolvi aqui para você paizão 

![Screenshot_2024-08-26-23-53-01-142_br.erickweil.portugolweb.jpg](https://github.com/user-attachments/assets/5999d32f-6a05-44c5-b3ca-e8ba45dd5084)

Apenas troque o randomico por sorteira:


programa
{
    funcao inicio()
    {
        // Variáveis
        inteiro numero_secreto, palpite, tentativas

        // Gera um número aleatório entre 1 e 100
        numero_secreto = sorteia(1, 100)
        tentativas = 0

        // Loop para o jogo de adivinhação
        enquanto (verdadeiro)
        {
            escreva("Digite o seu palpite (entre 1 e 100): ")
            leia(palpite)
            tentativas = tentativas + 1

            // Verifica se o palpite está correto
            se (palpite == numero_secreto)
            {
                escreva("Parabéns! Você acertou o número em ", tentativas, " tentativas.\n")
                pare // Sai do loop
            }
            senao se (palpite < numero_secreto)
            {
                escreva("O número secreto é maior.\n")
            }
            senao
            {
                escreva("O número secreto é menor.\n")
            }
        }
    }
}

Gostei demais do jogo, foi um bom exercício de lógica 🤟

**Comment by dgadelha** [comment]
Olá

Para usar a função `sorteia`, você deve incluir a biblioteca `Util`:

```portugol
programa {
  inclua biblioteca Util
  funcao inicio() {
    escreva(Util.sorteia(1, 100))
  }
}
```
