### ISSUE TITLE
INSATISFAÇÃO TOTAL

### ISSUE THREAD

**Issue by meropimentel** [dgadelha/Portugol-Webstudio#297]
### Descrição do problema

Estamos em um treinamento On Line, e a ferramenta apresenta constantes problemas, causando irritação pelo atraso em tentar resolver um problema de vocês ao invés de estarmos aprendendo estamos tentando burlar os ERROS DE VOCÊS para concluir o treinamento.    Tem hora que grava outra não, tem hora que renomeia as abas outras não, erros de funções... e assim vai a cada momento... UMA VERDADEIRA LOUCURA   

### Código

```portugol
programa {
  funcao inicio() {
    inteiro op, n1, n2
    limpa()
    escreva("\n=-=-=-=-=-=-=-  SISTEMA CALCULADORA  =-=-=-=-=-=-=-")
    escreva("\n1- SOMA  \n2- SUBTRAÇÃO  \n3- MULTIPLICAÇÃO  \n4- DIVISÃO  \n0- SAIR")
    escreva("\n---------------------------------------------------")    
    escreva("\nDigite Opção:  ")
    leia(op)
    escolha(op) {
      caso 1:
          escreva("\n\nATENÇÃO: Você escolheu a operação → SOMAR ←")
          escrva("\nDigite 1o.Valor: ")
          leia(n1)
          escreva("Digite 2o.Valor: ")
          leia(n2)
          escreva("\nA SOMA de "+n1+" + "+n2+" = "+n1+n2)
      caso 2:

      
    }

    
  }
}


tentamos gravar e não grava, tentamos renomear a aba e não renomeia,  loucura loucura loucura

Temos de reiniciar o navegador, ou mudar de navegador, as vezes reiniciar o computador, outras vezes esperar algumas horas para voltar a funcionar...
```

**Comment by dgadelha** [comment]
Boa tarde, @meropimentel

Você consegue gravar a tela com os problemas acontecendo e colocar aqui?

Se possível, incluir a versão do navegador que você está usando.

**Comment by meropimentel** [comment]
O Chrome está atualizado
Versão 128.0.6613.138 (Versão oficial) 64 bits
****************************************************
Microsoft Edge
Versão 128.0.2739.67 (Compilação oficial) (64 bits)
*****************************************************

programa 
{
  funcao inicio() 
  {
    inteiro n1, n2 = 0
    inteiro op = 1 
    limpa()
    escreva("\n=-=-=-=-=-=-=-  SISTEMA CALCULADORA  =-=-=-=-=-=-=-")
    escreva("\n1- SOMA  \n2- SUBTRAÇÃO  \n3- MULTIPLICAÇÃO  \n4- DIVISÃO  \n0- SAIR")
    escreva("\n---------------------------------------------------")   
    enquanto (op != 0)
    {

        escreva("\nDigite Opção:  ")
        leia(op)
        escolha(op) {
            caso 0:
              limpa()
              escreva("\n\n\n            ****   Você acaba de sair do sistema..!   ****")
              escreva("\n\n\n\n")
            pare
            caso 1:
              escreva("\n\n\nATENÇÃO: Você escolheu a operação → SOMAR ←")
              escreva("\nDigite 1o.Valor: ")
              leia(n1)
              escreva("Digite 2o.Valor: ")
              leia(n2)
              escreva("\nA SOMA de "+n1+" + "+n2+" = "+(n1+n2))
            caso 2:
              escreva("\n\n\nATENÇÃO: Você escolheu a operação → SUBTRAIR ←")
              escreva("\nDigite 1o.Valor: ")
              leia(n1)
              escreva("Digite 2o.Valor: ")
              leia(n2)
              escreva("\nA SUBTRAÇÃO de "+n1+" - "+n2+" = "+(n1-n2))
/*            caso contrario:
              escreva("opção ERRADA, digite novamente")    */
        } 

      
    }

    
  }
}

Treinamento para iniciante, comecei o código agora

**Comment by meropimentel** [comment]
> O Chrome está atualizado Versão 128.0.6613.138 (Versão oficial) 64 bits
> 
> Microsoft Edge Versão 128.0.2739.67 (Compilação oficial) (64 bits)
> 
> programa { funcao inicio() { inteiro n1, n2 = 0 inteiro op = 1 limpa() escrever("\n=-=-=-=-=-=-=- SISTEMA CALCULADORA =-=-=-=-= -=-=-") escrever("\n1- SOMA \n2- SUBTRAÇÃO \n3- MULTIPLICAÇÃO \n4- DIVISÃO \n0- SAIR") escrever("\n------------- --------------------------------------") enquanto (op != 0) {
> 
> ```
>     escreva("\nDigite Opção:  ")
>     leia(op)
>     escolha(op) {
>         caso 0:
>           limpa()
>           escreva("\n\n\n            ****   Você acaba de sair do sistema..!   ****")
>           escreva("\n\n\n\n")
>         pare
>         caso 1:
>           escreva("\n\n\nATENÇÃO: Você escolheu a operação → SOMAR ←")
>           escreva("\nDigite 1o.Valor: ")
>           leia(n1)
>           escreva("Digite 2o.Valor: ")
>           leia(n2)
>           escreva("\nA SOMA de "+n1+" + "+n2+" = "+(n1+n2))
>         caso 2:
>           escreva("\n\n\nATENÇÃO: Você escolheu a operação → SUBTRAIR ←")
>           escreva("\nDigite 1o.Valor: ")
>           leia(n1)
>           escreva("Digite 2o.Valor: ")
>           leia(n2)
>           escreva("\nA SUBTRAÇÃO de "+n1+" - "+n2+" = "+(n1-n2))
> ```
> 
> /* caso contrário: escrever("opção ERRADA, digite novamente") */ }
> 
> ```
> }
> ```
> 
> } }
> 
> Treinamento para iniciante, descobri o código agora



> Boa tarde,@meropimentel
> 
> Você consegue gravar a tela com os problemas acontecendo e colocar aqui?
> 
> Se possível, inclua a versão do navegador que você está usando.

**Comment by meropimentel** [comment]
O Chrome está atualizado Versão 128.0.6613.138 (Versão oficial) 64 bits

Microsoft Edge Versão 128.0.2739.67 (Compilação oficial) (64 bits)

https://github.com/user-attachments/assets/47bf6904-4006-4ca7-8455-2716b9da8cd3

**Comment by dgadelha** [comment]
Obrigado, vou analisar o problema.

**Comment by meropimentel** [comment]
Olá Dougla bom dia,

Consigo sim, mas se quiseres acesso via AnyDesk, posso te dar também

Estou desesperado, pois sou iniciante e querendo obter mais um conhecimento

Em sex., 13 de set. de 2024 às 13:18, Douglas Gadêlha <
***@***.***> escreveu:

**Comment by dgadelha** [comment]
@meropimentel, lancei uma nova versão, a `6040FFF`, que corrige o renomeio de abas.

Quando você clica em Salvar e não acontece nada, aparece algum erro no Console (ele abre quando você clica F12) do navegador?

**Comment by meropimentel** [comment]
Quando você clica em Salvar e não acontece nada, aparece algum erro no
Console
*NÃO,  NÃO APARECIA  NADA VISÍVEL .*

*VOU DAR ANDAMENTO NOS ESTUDOS AGORA  A NOITE, SE CASO OCORRER  ALGUM
PROBLEMA TE PASSO POR AQUI*

(ele abre quando você clica F12) do navegador?
*DESCULPAS, MAS REALMENTE NÃO TESTEI CLICANDO NO F12*

*CREIO QUE, COM A VERSÃO NOVA VOCÊ JÁ DEVA TER SOLUCIONADO O PROBLEMA.*
*VAMOS DAR ANDAMENTO NOS ESTUDOS E CONSEQUENTEMENTE NOS TESTE.*

*MUITÍSSIMO OBRIGADO PELO SUPORTE !!!!*


Em sex., 13 de set. de 2024 às 17:13, Douglas Gadêlha <
***@***.***> escreveu:

**Comment by meropimentel** [comment]
@meropimentel <https://github.com/meropimentel>, lancei uma nova versão, a
6040FFF, que corrige o renomeio de abas.
*VERDADE, JÁ CORRIGIDO, CONSIGO RENOMEAR*

AINDA APARECENDO MENSAGEM DE "BAIXANDO ATUALIZAÇÕES", mas já consigo
renomear
*******************************************************************************************************************

Quanto a questão da gravação, te encaminho abaixo, um pequeno código que
não grava

programa
{
  funcao inicio()
  {
    inteiro op, n1, n2
    escreva("=-=-=-=-=  MENU DE OPÇÕES  =-=-=-=-=")
    escreva("\n[1] SOMA  \n[2] SUBTRAÇÃO  \n[3] MULTIPLICAÇÃO \n[4] DIVISÃO
\nDigite sua opção: ")
    leia(op)
    escolha(op)
    {
      caso 1:
        escreva("\nVocê escolheu →  S O M A R  ←")
        escreva("\nDigite 1o. Número: ")
        leia(n1)
        escreva("Digite 2o. Número :")
        leia(n2)
        escreva("\nA SOMA de "+n1+" + "+n2+" = "+(n1+n2)+"\n")
      pare
      caso 2:
        escreva("\nVocê escolheu →  S U B T R A I R  ←")
        escreva("\nDigite 1o. Número: ")
        leia(n1)
        escreva("Digite 2o. Número: ")
        leia(n2)
        escreva("\nA SUBTRAÇÃO de "+n1+" - "+n2+" = "+(n1-n2)+"\n")
      pare
      caso 3:
        escreva("\nVocê escolheu →  M U L T I P L I C A R  ←")
        escreva("\nDigite 1o. Número: ")
        leia(n1)
        escreva("Digite 2o. Número: ")
        leia(n2)
        escreva("\nA MULTIPLICAÇÃO de "+n1+" * "+n2+" = "+(n1*n2)+"\n")
      pare
      caso 4:
        escreva("\nVocê escolheu →  D I V I D I R  ←")
        escreva("\nDigite 1o. Número: ")
        leia(n1)
        escreva("Digite 2o. Número: ")
        leia(n2)
        escreva("\nA DIVISÃO de "+n1+" / "+n2+" = "+(n1/n2)+"\n")
      pare
      caso contrario:
        escreva("\nATENÇÃO: Você digitou opção errada !\n\n")

    }

  }
}




Em sex., 13 de set. de 2024 às 17:13, Douglas Gadêlha <
***@***.***> escreveu:

**Comment by dgadelha** [comment]
@meropimentel, experimenta usar o https://beta.portugol.dev/

Pode ver se lá funciona tudo certinho?

**Comment by meropimentel** [comment]
SHOWWWWWWWW
Agora sim, inclusive você agregou o <SALVAR COMO>

Aleluia....

você é TOP
***********************************************************************************
Agora vou acompanhar a questão do auto complemento dos comandos.
Quero dizer o seguinte:
    Quando estamos digitando o comando "ESCREVER", basta digitar "ES" que
já vai aparecer as opções, isso economiza muito tempo de programação de um
código, que também não estava funcionando.

    Vou observar os detalhes sobre o citado e te faço um relato amanhã.

Abração meu irmão, e que Deus continue iluminando essa sua mente
capacitada...

Em sex., 13 de set. de 2024 às 22:14, Douglas Gadêlha <
***@***.***> escreveu:
