### ISSUE TITLE
// Algoritmo "Calculo Potenciacao" programa {     funcao inicio()     {         // Declaração de variáveis         inteiro a, b, resultado, i          // Obtendo os valores de a e b         escreva("Informe o valor de a (base): ")         leia(a)         escreva("Informe o valor de b (expoente): ")         leia(b)          // Inicializando resultado         resultado <- 1          // Cálculo da potenciação         i <- 1         enquanto (i <= b) faça         {             resultado <- resultado * a             i <- i + 1         }          // Impressão do resultado         escreva("Resultado de ", a, " elevado a ", b, " é: ", resultado)     } } // Fim algoritmo

### ISSUE THREAD

**Issue by Xandi-kross** [dgadelha/Portugol-Webstudio#302]
### Descrição do problema

// Algoritmo "Calculo Potenciacao"
programa
{
    funcao inicio()
    {
        // Declaração de variáveis
        inteiro a, b, resultado, i

        // Obtendo os valores de a e b
        escreva("Informe o valor de a (base): ")
        leia(a)
        escreva("Informe o valor de b (expoente): ")
        leia(b)

        // Inicializando resultado
        resultado <- 1

        // Cálculo da potenciação
        i <- 1
        enquanto (i <= b) faça
        {
            resultado <- resultado * a
            i <- i + 1
        }

        // Impressão do resultado
        escreva("Resultado de ", a, " elevado a ", b, " é: ", resultado)
    }
}
// Fim algoritmo

### Código

```portugol
// Algoritmo "Calculo Potenciacao"
programa
{
    funcao inicio()
    {
        // Declaração de variáveis
        inteiro a, b, resultado, i

        // Obtendo os valores de a e b
        escreva("Informe o valor de a (base): ")
        leia(a)
        escreva("Informe o valor de b (expoente): ")
        leia(b)

        // Inicializando resultado
        resultado <- 1

        // Cálculo da potenciação
        i <- 1
        enquanto (i <= b) faça
        {
            resultado <- resultado * a
            i <- i + 1
        }

        // Impressão do resultado
        escreva("Resultado de ", a, " elevado a ", b, " é: ", resultado)
    }
}
// Fim algoritmo
```

### Comentários adicionais

// Algoritmo "Calculo Potenciacao"
programa
{
    funcao inicio()
    {
        // Declaração de variáveis
        inteiro a, b, resultado, i

        // Obtendo os valores de a e b
        escreva("Informe o valor de a (base): ")
        leia(a)
        escreva("Informe o valor de b (expoente): ")
        leia(b)

        // Inicializando resultado
        resultado <- 1

        // Cálculo da potenciação
        i <- 1
        enquanto (i <= b) faça
        {
            resultado <- resultado * a
            i <- i + 1
        }

        // Impressão do resultado
        escreva("Resultado de ", a, " elevado a ", b, " é: ", resultado)
    }
}
// Fim algoritmo

**Comment by dgadelha** [comment]
Olá! Utilizar `<-` para atribuição ao invés de `=` indica o Portugol no formato Algol. O Portugol Webstudio dá suporte apenas ao Portugol no padrão UNIVALI.
