### ISSUE TITLE
Transformar o Código Portugol em Java ou Rodar o Portugol no Terminal

### ISSUE THREAD

**Issue by Windows87** [dgadelha/Portugol-Webstudio#31]
Como não fui respondido no repositório original, e a tecnologia que estou usando é NodeJS, vim perguntar aqui ¯\_(ツ)_/¯ 

Estou fazendo um corretor automático de exercícios (dando os valores de entrada pro programa e depois comparando os valores de saída esperados com os de saída do código submetido), consegui fazer com Python, queria fazer com o Portugol, mas não tenho nenhum conhecimento em Java para mexer no código fonte original (não consegui nem abrir o Portugol pelo código fonte ._.).

Minha ideia seria converter em Java e então fazer toda a mágica do corretor ou rodar o portugol direto pelo terminal e fazer a mágica acontecer.

Como vocês usam o Portugol na parte do servidor, alguma sugestão de como fazer isso que desejo fazer?

**Comment by Windows87** [comment]
Cinco minutos depois de mandar essa issue, fui ver os arquivos e achei o "portugol-console.jar", que é só eu mandar o comando no terminal "java -jar portugol-console.jar enderecoDoArquivo" que faz exatamente o que eu quero ¯\_(ツ)_/¯

**Comment by dgadelha** [comment]
Sim, [precisamos fazer modificações no Portugol para poder funcionar bem no Webstudio](https://github.com/dgadelha/Portugol-Studio/commit/f568baddcdb6e41be79ad3c7f5ad24eb70d8ae21), o arquivo Java gerado que você achou deve ser suficiente para você poder usar também :)
