### ISSUE TITLE
problema ao inserir valores em um vetor de cadeia (n sei se eu escrevi errado e n achei algo q me corrigisse)

### ISSUE THREAD

**Issue by ArielScarlate789** [dgadelha/Portugol-Webstudio#314]
### Descrição do problema

![imagem_2024-10-09_181106860](https://github.com/user-attachments/assets/00be580f-0a47-4df1-8d2b-d7afeb7c176e)

quando eu termino de inserir os valores nesse vetor, a compilação da um erro indefinido, digitei algo de errado?

### Código

```portugol
programa {
  funcao inicio() {
    cadeia palavra[3]
    para (inteiro int = 0; int<=3;int++) {
      escreva("digite uma palavra ")
      leia(palavra[int])
    }
    escreva(palavra[1])
    
  }
}
```

**Comment by dgadelha** [comment]
Olá

O problema é que você está tentando executar o `leia` num índice do vetor que não existe. O tamanho do vetor é 3, logo as posições são 0, 1 e 2. No `para`, você deixa o `int` ter o valor `3`, e ao salvar o valor da variável na posição 3, dá erro.

Vou deixar a issue aberta para melhorar a mensagem de erro.

**Comment by ArielScarlate789** [comment]
É q eu vi nos exemplos q parecia q dava pra definir o tamanho já inserindo
os valores os valores na hora, como com os numeros inteiros

Em sáb., 12 de out. de 2024, 23:14, Douglas Gadêlha <
***@***.***> escreveu:
