### ISSUE TITLE
Declarar variáveis 

### ISSUE THREAD

**Issue by Batuni** [dgadelha/Portugol-Webstudio#318]
### Descrição do problema

Nao consigo declara variaveis usando o simbolo "=", o programa nao le e diz que a variavel media nao foi declarada.

### Código

```portugol
programa {
  funcao inicio() {
  real nota1, nota2

  escreva("Digite a primeira nota: \n")
  leia(nota1)
  escreva("Voce digitou a nota ", nota1, ". \n")
        
  escreva("Digite a segunda nota: \n")
  leia(nota2)
  escreva("Voce digitou a nota ", nota2, ". \n")
        
  media = (nota1 + nota2) /2
  escreva("Sua média é: ", media, ". \n")

      }
    }
```

### Comentários adicionais

![Captura de tela 2024-10-23 105533](https://github.com/user-attachments/assets/5e81fcf1-ce5e-4fd8-9d3c-07e3f9c00f51)

**Comment by dgadelha** [comment]
Olá, você realmente esqueceu de declarar a variável `media`, ela pode estar tanto na linha 3, junto com `nota1` e `nota2` (ficando `real nota1, nota2, media`), ou você pode incluir a declaração na linha 13 (ficando `real media = (nota1 + nota2) /2`).
