### ISSUE TITLE
Problemas nas bibliotecas do portugol studio.

### ISSUE THREAD

**Issue by forti8** [dgadelha/Portugol-Webstudio#320]
### Descrição do problema

Algumas bibliotecas na versão web não funcionam corretamente, sendo elas Graficos, Mouse, Sons...
Elas são citadas no menu ajuda em uma lista de bibliotecas.

### Código

```portugol
programa {
  inclua biblioteca Graficos --> g
  funcao inicio () {
g.iniciar_modo_grafico(verdadeiro)
}
}
```

**Comment by dgadelha** [comment]
A biblioteca Graficos realmente ainda não está disponível no Portugol Webstudio.

Fechando como duplicada da #304.
