### ISSUE TITLE
Teria como por um exemplo de escolha caso mais de um caso com a mesma resposta? 

### ISSUE THREAD

**Issue by Uriel29** [dgadelha/Portugol-Webstudio#33]
Olá, adorei o Webstudio, tem me ajudado demais. Eu sempre fui um mexedor de código. 
Mas resolvi aprender de verdade, do zero. E estou começando com algoritmo 

Mas tive um problema em saber com fazer uma escolha onde mais de um caso resulta a mesma resposta. 
procurei na internet e não tinha resposta. 
Acabei sem querer vendo uma forma no php e reproduzi para tentar ver se era igual no Portugol. 

E era 
escolha(d)
{
	        
	        caso 1:
	        caso 2:
	        caso 3:
	        escreva("escolheu 1  ou 2 ou 3")
	        pare 
	        caso 5: 
	        escreva("escolheu o 5 ")
		caso contrario: 
		 escreva ("Opção Inválida !")
	        
}
Poderia ter um exemplo deste. Vários casos com a mesma resposta. 
Eu sofri muito para achar, e não achei. 
Não gostaria que iniciantes sofressem. 
Foi na sorte. 

Abraços

**Comment by dgadelha** [comment]
Olá!

Na seção de ajuda do Portugol Studio, em Estruturas de Controle -> Desvios Condicionais -> Escolha caso, isso está especificado como:

> Além disto, o escolha e o caso tem alguns casos testes, e se a instrução pare não for colocada ao fim de cada um destes testes, o comando executará todos casos existentes.

Infelizmente, não temos controle da seção de Ajuda ou de Exemplos, essa solicitação teria de ser feita ao time do [Portugol Studio](https://github.com/UNIVALI-LITE/Portugol-Studio).
