### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by diaseduardoo123** [dgadelha/Portugol-Webstudio#330]
### Descrição do problema

quero saber o erro do código

### Código

```portugol
programa {
  funcao inicio() {
    // Declaração de variáveis
inteiro num1, num2, num3

// Entrada de dados
escreva("Digite o primeiro número: ")
leia(num1)

escreva("Digite o segundo número: ")
leia(num2)

escreva("Digite o terceiro número: ")
leia(num3)

// Impressão do resultado
escreva("O menor número é: ", minimo(num1, minimo(num2, num3)))

  }
}
```

**Comment by ronneyns** [comment]
Correção: a função "minimo" não foi declarada. Se ela existe em alguma biblioteca, então você deve importar a biblioteca senão você deve implementar essa função.

Dica importante:
- quando estiver programando e der um erro de compilação ou de execução, leia com atenção a mensagem para poder analisar o que houve e fazer os devidos reparos no código.
