### ISSUE TITLE
Problema na soma

### ISSUE THREAD

**Issue by Tailan783** [dgadelha/Portugol-Webstudio#331]
### Descrição do problema

o programa n faz a soma, variavel não declarada

### Código

```portugol
programa {
  funcao inicio() {

  //Soma das dos elementos das matrizes//

    inteiro matriz[10][10] = 
    {

    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},

    {10, 9, 8, 7, 6, 5, 4, 3, 2, 1},

    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},

    {10, 9, 8, 7, 6, 5, 4, 3, 2, 1},

    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},

    {10, 9, 8, 7, 6, 5, 4, 3, 2, 1},

    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},

    {10, 9, 8, 7, 6, 5, 4, 3, 2, 1},

    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},

    {10, 9, 8, 7, 6, 5, 4, 3, 2, 1}
}
  para (inteiro i = 0; i < 10; i++ ) {
      para (inteiro j = 0; j < 10; j++) 
    {   
     soma = soma + matriz[i][j]
    }
  }
  escreva ("a soma dos elementos das matrizes é: ", soma)

  }
}
```

**Comment by ronneyns** [comment]
Correção: a variável "soma" não foi declarada.

Dicas importantes:
- quando estiver programando e der um erro de compilação ou de execução, leia com atenção a mensagem para poder analisar o que houve e fazer os devidos reparos no código;
- sempre que for acumular valores, você deve inicializar a variável de acumulação com 0 (zero) se for um somatório (a + b + c + ...) ou 1 (um) se for um produtório (a * b * c * ...). A razão disso é porque você não sabe qual o valor inicial de uma variável assim que você a "cria", então deve garantir que tenha um valor inicial adequado para o que você quer fazer.
