### ISSUE TITLE
código

### ISSUE THREAD

**Issue by Lasilva8** [dgadelha/Portugol-Webstudio#334]
### Descrição do problema

- O seu programa irá iniciar abaixo -

⛔ Função não declarada: excreva

Porém, todas as variáveis foram devidamente declaradas
![Captura de tela 2024-11-14 195828](https://github.com/user-attachments/assets/7c0dd3d4-2298-488d-9fcd-80ab2423e4e0)

### Código

```portugol
programa 
{    inclua biblioteca Matematica-->mat
 funcao inicio() 
 {
 // Algoritmo de Potenciacao

//PROGRAMA DE POTENCIA

real valor, expoente
excreva("digite um valor: ")
leia(valor)
escrever("digite um expoente: ")


//INICIO

ESCREVA("Digite o valor de A: ")
LEIA(a)

ESCREVA("Digite o valor de B: ")
LEIA(b)

resultado ':=' 1

PARA i DE 1 ATE b FACA

resultado ':=' resultado * a


ESCREVA("O resultado de ", A, " elevado a ", B, " é: ", resultado)
FIM_PARA
    
  }
}
```

### Comentários adicionais

Me ajudem por favor

**Comment by gersonbonetti** [comment]
Creio que o problema não é do projeto, mas da sua estrutura de código. Existem muitas inconsistências nele. Você usou ```_excreva()_```, ```_escrever()_``` e ```_ESCREVA()_```. Se você usar ```_escreva()_``` já é o suficiente.

Além disso, você não fez a captura da variável do expoente utilizando o ```leia()```.

Tente as seguintes alterações:
- Retirar a importação da biblioteca
- O operador de atribuição é o ```=```, e não o ```:=```
- Declare variáveis que você irá utilizar durante a execução (```valor``` e ```expoente``` não estão sendo usados)
- O seu loop está confuso. Você pode usar algo assim ```para (i = 1; i <= b; i++)```

Depois dessas alterações, tente novamente.
