### ISSUE TITLE
Operador

### ISSUE THREAD

**Issue by Chris2197** [dgadelha/Portugol-Webstudio#342]
### Descrição do problema

Ao tentar executar o código, a IDE exibe um erro de sintexe ao usar a função "operador"

### Código

```portugol
programa
  {
  funcao inicio()
   {
    caracter operadoor
    real resultado = 0.0, operando1, operando2

    escreva("digite o primeiro número: ")
    leia(operando1)

    escreva("digite o segundo número: ")
    leia(operando2)

    escreva("\n")

    escreva("agora digite uma das operações ( + - * / ): ")
    leia(operador)
    
    /* Verifica qual foi a operação selecionada */
    
    se (operador == '+')
    {
      resultado = operando1 + operando2

    }
    senao se(operador == '-')
    {
      resultado = operando1 / operando2
    }
  }
}
```

### Comentários adicionais

O seu código possui 5 erros de compilação:
   - Variável não declarada: operando (linha 15, posição 9)
   - Variável não declarada: operando (linha 19, posição 8)
   - Variável não declarada: operandor2 (linha 21, posição 30)
   - Variável não declarada: operandor2 (linha 21, posição 30)
   - Variável não declarada: operando (linha 24, posição 13)

**Comment by dgadelha** [comment]
Olá! Você declarou a variável `operadoor` e usou ela como `operador`.
