### ISSUE TITLE
Outra opção de exibir o link para compartilhar código

### ISSUE THREAD

**Issue by leandro-costa** [dgadelha/Portugol-Webstudio#38]
Quando https://portugol-webstudio.cubos.io/ide é colocado para rodar embarcado em algum SW utilizando Electron (Ex Microsoft Teams) e clica no "Gera um link do programa atual para ser compartilhado na internet" o link não é exibido. Acredito que seja  porque utiliza "window.prompt" para exibir. 
É possível alterar para mostrar dentro da pagina?

**Comment by dgadelha** [comment]
Alterei para utilizar o Modal do Bootstrap, deve funcionar no Teams

![image](https://user-images.githubusercontent.com/10081640/99190797-58265300-2747-11eb-9449-f27f106153e3.png)
