### ISSUE TITLE
Abrir fonte em uma URL

### ISSUE THREAD

**Issue by nobnet** [dgadelha/Portugol-Webstudio#47]
É possível abrir um fonte em uma URL, por exemplo, do github?
Por exemplo: portugol-webstudio.cubos.io/ide?src=https://github.com/meuGit/fonte.por

Embora tenha o recurso de links compartilhados, esses expiram. Então, a única forma de provê-los, por exemplo, em um caderno do jupyter, seria com links externos.
É possível?

**Comment by dgadelha** [comment]
Acabei deixando essa issue passar sem querer. Isso é implementável sim, só não sei um jeito bom de colocar na interface, mas consigo implementar um jeito básico pra já permitir que você faça uso disso.

**Comment by nobnet** [comment]
Muito obrigado. Será muito útil, enquanto não temos um kernel implementado no jupyter.

**Comment by dgadelha** [comment]
@nobnet, por curiosidade, as URLs que você quer carregar, terminam com as extensões .POR ou .TXT? assim como https://raw.githubusercontent.com/UNIVALI-LITE/Portugol-Studio/master/ide/src/main/assets/exemplos/algoritmos_sequenciais/altura_media.por

Por motivo de CORS, tive que fazer proxy da URL pelo servidor, e por segurança não quero permitir que qualquer URL seja aberta

**Comment by nobnet** [comment]
Apenas .POR. 
Obrigado.

**Comment by dgadelha** [comment]
@nobnet, acabei de fazer deploy dessa mudança, basta adicionar `#url=` no final da URL da IDE, por exemplo:

```https://portugol-webstudio.cubos.io/ide#url=https://raw.githubusercontent.com/UNIVALI-LITE/Portugol-Studio/master/ide/src/main/assets/exemplos/algoritmos_sequenciais/altura_media.por```
