### ISSUE TITLE
Bloquear o envio de palavras reservadas por input

### ISSUE THREAD

**Issue by guiscaranse** [dgadelha/Portugol-Webstudio#6]
Uma vez que o [base.js](https://github.com/dgadelha/Portugol-Webstudio/blob/master/sockets/base.js) responde a leituras do terminal, não deve-se permitir enviar palavras reservadas identificadas por `~|^!+PALAVRA+!^|~` que poderiam interromper a execução do programa ou travar o sistema.

**Comment by dgadelha** [comment]
Dá até pra meter isso direto no console do Portugol, substituir elas por algo tipo "Palavra reservada". Eu posso fazer.

**Comment by guiscaranse** [comment]
A ordem que o input passa é:
1. base.js
2. runtime.py
3. Java

Esse problema do input está no base.js, pois quando o input for enviado e for escrito no terminal ele vai interpretar como uma palavra reservada de comando.
Passos para testar:
1. Executar o seguinte código
```
programa
{
	funcao inicio ()
	{
		cadeia nome

		escreva("Digite seu nome: ")
		leia(nome)

		escreva("Seu nome é: ", nome, "\n")
	}
}
```
2. Quando o input for selecionado, enviar: `~|^!+END+!^|~`
O programa teoricamente vai travar nesse momento, pois o base.js vai interpretar que o programa retornou um `~|^!+END+!^|~`

**Comment by guiscaranse** [comment]
Seria legal implementar o que tu disse para eu retirar o filtro que eu escrevi no python, nesse [commit](https://github.com/dgadelha/Portugol-Webstudio/commit/7701cc3eb2b48b522b394783eb0dd6fc141fab46) e retornar o erro no próprio .jar, para unificar essas coisas mas ainda fazer esse filtro que eu citei acima.
Algo tipo, "ERRO! Palavra reservada proibida" e talz

**Comment by dgadelha** [comment]
Quanto às bibliotecas, acho que consigo desativar elas direto no núcleo. O resto eu vou dar uma olhada.

**Comment by AlissonSteffens** [comment]
Nó utilizamos a abordagem de analisadores sintáticos e semânticos, antes de compilar. Acho que se vocês fizerem uma análise assim antes de enviar para execução o problema será resolvido, e já da de evitar outros comportamento inesperados.

**Comment by AlissonSteffens** [comment]
Para remover as libs é só não instalar elas, nesta parte do código
https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/master/src/br/univali/portugol/nucleo/bibliotecas/base/GerenciadorBibliotecas.java#L84
, remova as libs que vc não quer, e GG

**Comment by dgadelha** [comment]
Opa, valeu mano!
