### ISSUE TITLE
Operação de deslocamento bit-a-bit

### ISSUE THREAD

**Issue by StelmoNetto** [dgadelha/Portugol-Webstudio#61]
Boa tarde.
Parece que o comportamento da nova versão não corresponde à versão anterior, no que tange às operações bit-a-bit, em especial a de deslocamento.
O código abaixo funciona bem na versão anterior, mas não na experimental:
https://dgadelha.github.io/Portugol-Webstudio/#share=c33ddzw

Obrigado pela ferramenta

**Comment by dngadelha** [comment]
Olá, @StelmoNetto!

Primeiramente obrigado por reportar o problema.

Analisando seu código pude identificar que o problema não é nas operações de deslocamento bit-a-bit e sim no operador `+=`.

Na linha 17 do seu código, ao substituir:

```javascript
numeroDeNibblesDeslocados += NIBBLE
```

por: 

```javascript
numeroDeNibblesDeslocados = numeroDeNibblesDeslocados + NIBBLE
```

O código funciona normalmente igual na versão anterior.

Atualmente não temos suporte a esse operador e iremos colocá-lo assim que possível.

**Comment by dgadelha** [comment]
Resolvido via #63
