### ISSUE TITLE
Melhorar o .travis.yml para compilar corretamente

### ISSUE THREAD

**Issue by guiscaranse** [dgadelha/Portugol-Webstudio#7]
O Travis atualmente está realizando apenas o deploy, é necessário compilar corretamente o pip3, Python3 e pty.js para que ele execute `npm install` corretamente.

**Comment by AlissonSteffens** [comment]
<pre>
PS D:\Documents\Git\Portugol-Webstudio> npm install

> portugol-webstudio@1.0.0 preinstall D:\Documents\Git\Portugol-Webstudio
> pip3 install pexpect

Requirement already satisfied: pexpect in c:\users\alisson\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: ptyprocess>=0.5 in c:\users\alisson\appdata\local\programs\python\python36-32\lib\site-packages (from pexpect)

> pty.js@0.3.1 install D:\Documents\Git\Portugol-Webstudio\node_modules\pty.js
> node-gyp rebuild


D:\Documents\Git\Portugol-Webstudio\node_modules\pty.js>if not defined npm_config_node_gyp (node "D:\Programs\Node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Alisson\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Programs\Node\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Programs\Node\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Programs\Node\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Programs\\Node\\node.exe" "D:\\Programs\\Node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\Git\Portugol-Webstudio\node_modules\pty.js
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash.isarguments@3.1.0 (node_modules\lodash.isarguments):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'D:\Documents\Git\Portugol-Webstudio\node_modules\lodash.isarguments\package.j
son.3763643871' -> 'D:\Documents\Git\Portugol-Webstudio\node_modules\lodash.isarguments\package.json'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alisson\AppData\Roaming\npm-cache\_logs\2017-07-07T02_13_32_725Z-debug.log
</pre>

**Comment by guiscaranse** [comment]
Olá @AlissonSteffens!
O problema pelo qual você não está conseguindo compilar e não irá conseguir compilar em sua máquina se da por dois motivos:
1. O erro do node-gyp se da por ele não estar encontrando o python em seu computador, você pode notar a saída dele nesta linha:
`Error: Can't find Python executable "C:\Users\Alisson\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.`
2. Esta versão do Webstudio ainda está em um Alpha, ou seja, não é a versão final ainda. Por este motivo não portei o código para `Windows` ainda. Então você não deverá conseguir compilar sem fazer algumas alterações na chamada. As alterações neste caso são nos arquivos [base.js](https://github.com/dgadelha/Portugol-Webstudio/blob/master/sockets/base.js#L7) e [runtime.py](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime.py#L24) nas respectivas linhas marcadas. O principal motivo de não ter realizado o porte para o Windows ainda é o anexo do terminal, que por padrão indexa o `xterm` no linux e no windows deveria indexar o `cmd`.

> Realmente precisa ter tanta lib assim??
A respeito das libs na prática só são usadas 3 essenciais:
1. pty.js (node)
2. pexpect (python)
3. express
Mas se você observar o `package.json` existirão muito mais dependências ali. Estas dependências são complementos das acima citadas, e embora ocupem um espaço considerável no `node_modules`, são bastante leves (amém V8). Tentei manter apenas o essencial para lá, mas com o tempo devo começar a descontinuar o suporte a elas.
A versão final já estará livre desses problemas.

A repeito do Travis, o problema dele é que é MUITO complicado realizar a compilação de projetos que utilizam duas línguas já que o `.travis.yml` normalmente é padronizado para uma apenas. Quando definido para compilar node.js ele tem preparado uma imagem de Python 2, o que não é suportado por nós.

**Comment by guiscaranse** [comment]
Abri uma issue para manter acompanhamento sobre o problema do windows ( #8 )

**Comment by dgadelha** [comment]
Qualquer coisa, [tamo rodando aqui](http://sf1.hashbang.sh:3000/) o projeto
