### ISSUE TITLE
Adicionar suporte para Windows

### ISSUE THREAD

**Issue by guiscaranse** [dgadelha/Portugol-Webstudio#8]
- [ ] Compilar binário de runtime.py para Windows
- [ ] Substituir pty.js para [node-pty](https://github.com/Tyriar/node-pty)
- [ ] Adicionar escolha de terminal para funcionar tanto no Windows como Linux. (pty.js)
- [x] Modificar forma de invocar processos para funcionar no Windows (runtime.py)

**Comment by guiscaranse** [comment]
É necessário compilar os [binários](https://github.com/dgadelha/Portugol-Webstudio/commit/9741bb99b2973bd6dfaaf9a519cc04ebe279754e) manualmente no Windows, o que não será prioridade agora.

**Comment by AlissonSteffens** [comment]
Passa ai o que tem que ser feito que eu faço 👍

**Comment by guiscaranse** [comment]
Olá @AlissonSteffens. É necessário compilar um binário de [runtime.py](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime/runtime.py). Para fazer isso você precisa instalar no Windows, você precisará de Python **3.5** e as dependências que eu informei neste [README](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime/README.md) (Pode descartar o UPX se desejar).
É recomendado que você faça um Virtualenv próprio com apenas as dependências de runtime.py para evitar que o Pyinstaller compacte código desnecessário. Você pode usar o mesmo comando que está declarado no README.
É recomendado testar o binário direto do console, se for possível executá-lo diretamente do console quer dizer que a compilação foi bem sucedida. Você pode testá-lo escrevendo ``~|^!+RUNTIME+!^|~teste.por` no input que ele aguardará, e retornará um erro (o que é normal já que teste.por não aponta para nenhum lugar).

Após compilar o binário, crie uma pasta e dentro de `/libs/runtime/` chamada `windows` e coloque **apenas o binário lá** (descarte todas as pastas e arquivos desnecessários).

É necessário também alterar a lib pty.js para [node-pty](https://github.com/Tyriar/node-pty) não é necessário alterar o resto do código, apenas a chamada da lib.
