### ISSUE TITLE
Retorno de valor em condição não é identificado

### ISSUE THREAD

**Issue by web-simm** [dgadelha/Portugol-Webstudio#84]
programa {
  inteiro N
  cadeia R
  funcao inicio() {
    escreva("Digite um número -> ")
    leia(N)
    R=parOUimpar(N)
    escreva("\nO número ",N," digitado é ",R)
  }
  funcao parOUimpar(inteiro &V){
    se(V%2==0){
      retorne "Par"
    }senao{
      retorne "Impar"
    }
  }
}

**Comment by dgadelha** [comment]
Obrigado pelo report!

**Comment by dgadelha** [comment]
Corrigido via https://github.com/dgadelha/Portugol-Webstudio/commit/41ba34afec8c0a83f2aecd6e94a2c01bc66c05c7
