### ISSUE TITLE
Atribuição de valor inteiro a variável real

### ISSUE THREAD

**Issue by aarosanunes** [dgadelha/Portugol-Webstudio#85]
real vetor [4] 
    real arredondamento

     
   para (inteiro i = 0; 1 <  4; i++)
   escreva("Digite o valor da mesa " + (i+1) ": ")
   leia(valorMesas[i])

   para (inteiro i = 0; i < 4, i++){
   se (vetor[i] > 30.99){
       vetor [i] = vetor [i] - 30.99
       vetor [i] = mat.arredondar (vetor [i], 2)
   }
      escreva("Mesa "+ (i+1) "Precisa pagar R$ ", vetor [i], "\n")
   }
   senao
      escreva("Mesa "+(i+1), "nada a pagar!\n ")

**Comment by aarosanunes** [comment]
Corrigindo a lição, Atividade 3, questão 1.
Em breve postarei mais de minhas atividades e futuros projetos. 

Segue texto:

programa
{
	inclua biblioteca Matematica--> mat
	
	funcao inicio()
	{    inteiro i
		real soma, mesa
		real valorMesa[4]
		real arrendodamento

		soma = 0
		para ( i = 0; i < 4; i++){
		escreva ("Digite o valor da mesa: " + (i+1) + ": ")
          
          leia (valorMesa[i])
          }

          para ( i = 0; i < 4; i++)
          se (valorMesa[i] > 30.99) {
          valorMesa[i] = valorMesa[i] - 30.99
          valorMesa[i] = mat.arredondar ( valorMesa [i], 2)
          escreva ("Mesa " + (i+1) + " :precisa pagar R$ ", valorMesa[i], "\n")
          }
          senao {
          	escreva ("Mesa " + (i+1) + " :nada a pagar!\n")
            
	    }
	}
}

**Comment by dgadelha** [comment]
Obrigado pelo report!
