### ISSUE TITLE
Variáveis em outro escopo são identificadas como definidas em outro escopo

### ISSUE THREAD

**Issue by flavioBrito7** [dgadelha/Portugol-Webstudio#88]
programa
{
	//DefiniÃ§Ã£o das constantes
	const inteiro LOTACAO = 3
	const cadeia CABECALHO = "\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  HOTEL CALIFÃ“RNIA  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n"
    	const cadeia SAUDACAO = "\nSeja bem-vindo!\n"
    	const cadeia TITULO_CHECKIN = "\n>>>>>>>>>  SISTEMA DE CHECK-IN  <<<<<<<<<\n"
    	const real DIARIA = 100.0
	//DefiniÃ§Ã£o das variÃ¡veis	
	cadeia nomeHospede[LOTACAO], nome, cpfHospede[LOTACAO], cpf
	real despesasHospede[LOTACAO], despesa = 0.0
	inteiro qtdeDiasHospedagem[LOTACAO], qtdeDias, opcao, indiceHospede = 0
	caracter continuar = 'S', cadastrar = 'S'
	
	funcao inicio()
	{
		faca{
			menu()
			leia(opcao)
			
			escolha(opcao){			
				caso 1:									
					enquanto(continuar == 'S'){
						cadastrarHospede()	
						escreva("\n\nVoltar ao menu? [S/N]")
						leia(continuar)
					}		
					pare			
				
				caso 2:				
					enquanto(continuar != 'S'){
					limpa()
					escreva("\nEXIBINDO HÃ“SPEDES CADASTRADOS...\n")
						para(inteiro i = 0; i < LOTACAO; i++){
							para(inteiro j = 0; j < 3; j++){
								escreva(" - ",nomeHospede[i], "\n")
								}
						}
					escreva("\n\nVoltar ao menu? [S/N]")
					leia(continuar)
					}
				pare
				
				caso 3:
					limpa()
					escreva("\nVocÃª escolheu a opÃ§Ã£o 3")
				pare
				
				caso 4:
					limpa()
					escreva("\nVocÃª escolheu a opÃ§Ã£o 4")
				pare
				
				/*caso contrario:
					limpa()
					escreva("\nVocÃª escolheu uma opÃ§Ã£o invÃ¡lida\n")*/
		}limpa()
		escreva("\n\nVocÃª digitou a opÃ§Ã£o 0: saindo do sistema HOTEL CALIFÃ“RNIA...\n")
		
		}enquanto(opcao!=0)
		
	}

	funcao menu(){
		limpa()
		escreva(CABECALHO, SAUDACAO)
		escreva("\nDigite a opÃ§Ã£o desejada: \n\n")		
		escreva("1. Cadastrar HÃ³spede  |  2. Exibir HÃ³spedes Cadastrados  |  3. Reservar Ãrea de Lazer  |  4. Calcular Total a Pagar  |  0. Sair\n")				
		}
		
	funcao cadastrarHospede(){
		limpa()
		escreva(TITULO_CHECKIN)
		escreva("\n\nCadastro do HÃ³spede:\n\n")
			enquanto((indiceHospede < LOTACAO) e (continuar != 'N')){
				para(inteiro i = 0; i < LOTACAO; i++){
					para(inteiro j = 0; j < 3; j++){						
						enquanto(cadastrar != 'N'){
							limpa()
							escreva(TITULO_CHECKIN)
							escreva("\n\nCadastro do HÃ³spede:\n\n")					
							escreva("Digite o nome: ")
							leia(nome)
								nomeHospede[i] = nome								
							escreva("Digite o CPF: ")
							leia(cpf)
								cpfHospede[i] = cpf						
							escreva("Digite a quantidade de diÃ¡rias: ")
							leia(qtdeDias)
								qtdeDiasHospedagem[i] = qtdeDias
								despesasHospede[i] = despesa																													
							limpa()							
							escreva("\n-------------------------------\nDESCRIÃ‡ÃƒO DO CADASTRO\n")
							escreva("\nNOME: ", nome, "\nCPF: ", cpf, "\n", qtdeDias," DIÃRIAS.\n-------------------------------\nHÃ³spede cadastrado(a) com sucesso!")							

								indiceHospede++
								
							escreva("\n\nDeseja cadastrar mais hÃ³spedes? [S/N]:")
							leia(cadastrar)														
							}
								se(cadastrar != 'S'){
									limpa()
									escreva(CABECALHO)
									escreva("\n",indiceHospede," HÓSPEDE(S) CADASTRADO(S):\n\n")
										para(inteiro k = 0; k <= indiceHospede-1; k++){
												escreva(" - ",nomeHospede[k], "\n")
										}	
									}
						escreva("\n...CADASTRO ENCERRADO\n")																			
						}	
			escreva("\nDeseja continuar? [S/N]:")
			leia(continuar)																									
			}

			limpa()	
			//Teste do limite do vetor de hÃ³spedes																		
			}
			se(indiceHospede == LOTACAO){															
				limpa()
				escreva(TITULO_CHECKIN)
				escreva("\nNÃ£o hÃ¡ mais quartos disponÃ­veis no momento...\n\n")
				escreva("\n",indiceHospede," HÓSPEDE(S) CADASTRADO(S):\n\n")
					para(inteiro k = 0; k < indiceHospede; k++){
							escreva(" - ",nomeHospede[k], "\n")
						}
					}
				escreva("\n------------------------------\nLIMITE DE HOSPEDAGENS ATINGIDO!\n------------------------------\n\n")															
																
		escreva("\n\nDeseja continuar? [S/N]:")
		leia(continuar)
		limpa()																										
	}
}

/* $$$ Portugol Studio $$$ 
 * 
 * Esta seÃ§Ã£o do arquivo guarda informaÃ§Ãµes do Portugol Studio.
 * VocÃª pode apagÃ¡-la se estiver utilizando outro editor.
 * 
 * @POSICAO-CURSOR = 4055; 
 * @PONTOS-DE-PARADA = ;
 * @SIMBOLOS-INSPECIONADOS = ;
 * @FILTRO-ARVORE-TIPOS-DE-DADO = inteiro, real, logico, cadeia, caracter, vazio;
 * @FILTRO-ARVORE-TIPOS-DE-SIMBOLO = variavel, vetor, matriz, funcao;
 */

**Comment by dgadelha** [comment]
Obrigado pelo report!
