### ISSUE TITLE
O seu código possui 1 erro de compilação:    - Expressão inválida: <missing '('> (linha 5, posição 5)

### ISSUE THREAD

**Issue by Pirelli236** [dgadelha/Portugol-Webstudio#89]
programa

funcao Maximo(a, b)
{
    se a > b entao
        retorne a
    senao
        retorne b
}

funcao inicio()
{
    inteiro numero_convidados
    inteiro cadeiras_adicionais

    escreva("Digite o número de convidados: ")
    leia(numero_convidados)

    se (numero_convidados < 0) ou (numero_convidados > 350) entao
        escreva("Número de convidados inválido")
    senao
        se (numero_convidados <= 150) entao
            escreva("Use o auditório Alfa")
            cadeiras_adicionais <- Maximo(0, numero_convidados - 150)
            se (cadeiras_adicionais > 0) entao
                escreva("Inclua mais ", cadeiras_adicionais, " cadeiras")
            fimse
        senao
            escreva("Use o auditório Beta")
        fimse
    fimse
}

**Comment by dgadelha** [comment]
Este código se trata de um código de Algol, não Portugol.
