### ISSUE TITLE
Documentação do runtime.py

### ISSUE THREAD

**Issue by servitoroftheoutergods** [dgadelha/Portugol-Webstudio#9]
O que exatamente o arquivo runtime.py, em libs/runtime, faz ou deve fazer?
Estou querendo reescrever, mas preciso saber o que faz exatamente, para poder documentar as funções

**Comment by guiscaranse** [comment]
A lib que a gente usa para emular o console é o Pty.js, porém, por ele ser um emulador do terminal seria imprudente liberar um shell direto linux para os usuário. É aí que entra o runtime.py, ele é de certa forma um intermediário entre o usuário e o servidor.
No runtime.py ocorrem as seguintes funções:

- [Iniciar/Interromper o processo Java do Portugol](https://github.com/dgadelha/Portugol-Webstudio/blob/c77cc160ece1dd3f587763c128ee28ee455e0708/libs/runtime/runtime.py#L52)
- [Indicar quando um programa em portugol inicia ou para](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime/runtime.py#L44-L61)
- [Interromper um programa automaticamente após 5 min de espera, para o processo não ficar para sempre ali](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime/runtime.py#L6-L23)
- [Fazer filtragem de palavras que mandam comandos para o NodeJS](https://github.com/dgadelha/Portugol-Webstudio/blob/master/libs/runtime/runtime.py#L31-L35)

Para entender como o runtime.py se comunica com o node, enviando esses indicativos, é possível analisar pelo [base.js](https://github.com/dgadelha/Portugol-Webstudio/blob/master/sockets/base.js) que está melhor documentado.

Espero que tenha ficado claro, caso contrário, estou a disposição
