### ISSUE TITLE
 função que recebe um número inteiro por parâmetro e retorna verdadeiro se ele for par e falso se for ímpar. 

### ISSUE THREAD

**Issue by Otavioalv** [dgadelha/Portugol-Webstudio#90]
programa {
  /* 
    2  Faça uma função que recebe um número inteiro por parâmetro e retorna verdadeiro se ele for par e falso se for ímpar. 

O seu código possui 1 erro de compilação:
   - A função 'comparar' deve retornar um valor (linha 17, posição 3)

⚠️ Durante essa fase experimental, o código ainda será executado mesmo com erros, porém se não corrigi-los, a execução abaixo pode exibir mensagens de erro em inglês ou sem explicação.
  */
  funcao inicio() {
    inteiro num
    logico comp

    escreva("digite um numero: ")
    leia(num)

    comp = comparar(num) // funciona perfeitamente

    escreva(comp)
  }

  funcao logico comparar(inteiro num) { // a função (comparar) retorna 2 valores
    se(num % 2 == 1) {
      retorne falso
    } senao {
      retorne verdadeiro
    }
  }
}

**Comment by dgadelha** [comment]
Obrigado pelo report! Trackeando na #84
