### ISSUE TITLE
Soma

### ISSUE THREAD

**Issue by Leenzera** [dgadelha/Portugol-Webstudio#92]
1 - Algoritmo MatrizRetangular
2 -      Var mat: vetor[1..2, 1..3] de inteiro
3 -            i: inteiro
4 -            j: inteiro
5 -      i ← 1
6 -      j ← 1
7 -      Enquanto i <= 2 faça
8 -            Enquanto j <= 3 faça
9 -                 mat[i,j] ← 1
10 -                 j ← j + 1
11 -            Fim_enquanto
12 -            i ← i + 1
13 -            j ← 1
14 -      Fim_enquanto
15 - Fim_algoritmo

**Comment by dgadelha** [comment]
Este código se trata de um código Algol, não Portugol.
