### ISSUE TITLE
Erro na linha 25- Erro desconhecido

### ISSUE THREAD

**Issue by GNRTRANSITO112** [dgadelha/Portugol-Webstudio#93]
programa {

  inclua biblioteca Matematica --> mat

  funcao inicio() {
    
    inteiro notas1, notas2
    real media

      escreva("Qual é sua nota: ")
      leia(notas1)
      escreva("Qual é a outra nota: ")
      leia(notas2)

      media=(notas1 + notas2) / 2

      limpa()

      se(media>=10)
    {
      escreva("\nAprovado!\n",media)
    }
    senao
    
      Se(media<5)
    {
      escreva("\nReprovado!\n",media)
    }
      Se(media>=5) (media<=10)
    {
      escreva("\nRecuperação\n",media)
    }
  }
}

**Comment by dgadelha** [comment]
Olá,

O erro está na última condição:
```
Se(media>=5) (media<=10)
```
O correto seria:
```
se((media>=5) e (media<=10)) {
```
