### ISSUE TITLE
qual o erro?

### ISSUE THREAD

**Issue by Batataquente1234** [dgadelha/Portugol-Webstudio#94]
programa {
  funcao inicio() 
  {
    Var preco, taxa: real
  Inicio
  Escreval  ("Qual o preço ")
Leia (preco)
preco <- preco + preco * 0.23
Escreval  ("Preço final ", preco)
Escreval ("Qual o preço do outro produto? ")
Leia (preco)
preco <- preco + preco * 0.23
Escreval ("Preço final ", preco)
FimAlgoritmo
  }

**Comment by dgadelha** [comment]
Este código está em Algol, não em Portugol.
