### ISSUE TITLE
MatrizRetangular

### ISSUE THREAD

**Issue by VaLFoR15** [dgadelha/Portugol-Webstudio#99]
1 - Algoritmo "MatrizRetangular"
2 -      Var mat: vetor[1..2, 1..3] de inteiro
3 -            i: inteiro
4 -            j: inteiro
5 -      i <- 0
6 -      j <- 0
7 -      Enquanto i <= 3 faça
8 -            Enquanto j <= 2 faça
9 -                 mat[i,j] <- 1
10-                  j <- j + 1
11 -            Fim_enquanto
12-       Fim_enquanto
13- Fim_algoritmo

preciso de ajuda pra resolver isso

**Comment by VaLFoR15** [comment]
1 - Algoritmo "MatrizRetangular"
2 -      Var mat: vetor[1..2, 1..3] de inteiro
3 -            i: inteiro
4 -            j: inteiro
5 -      i <- 0
6 -      j <- 0
7 -      Enquanto i <= 3 faça
8 -            Enquanto j <= 2 faça
9 -                 mat[i,j] <- 1
10-                  j <- j + 1
11 -            Fim_enquanto
12-       Fim_enquanto
13- Fim_algoritmo

**Comment by dgadelha** [comment]
Olá, esse algoritmo está em formato Algol, não no Portugol suportado pela plataforma.
